$serviceCards = @"
<div class="service-grid primary-services five-services">
  <article class="service-card service-bankruptcy"><p class="service-number">01</p><h2>Bankruptcy Operations</h2><p>Pre-filing, calculation, filing-readiness and post-filing bankruptcy operations for debtor, creditor, lender and servicer workflows.<span class="card-detail">Intake and document preparation; income and expense calculations; means-test and schedule preparation; creditor matrix; filing-readiness review; filed-case setup; PACER and docket tracking; trustee document requests; hearings and deadlines; claims and proof-of-claim preparation; amendments; Chapter 7 and Chapter 13 case events; payment and cure records; discharge, dismissal, conversion and case closure.</span></p><a href="$BasePath/services/bankruptcy-operations.html">Explore Bankruptcy Operations</a></article>
  <article class="service-card service-mortgage"><p class="service-number">02</p><h2>Mortgage Servicing and Default Operations</h2><p>Mortgage and default process services covering loan records, account reconciliation, delinquency, loss-mitigation administration, foreclosure tracking, bankruptcy and post-foreclosure records.</p><a href="$BasePath/services/mortgage-servicing-default-operations.html">Explore Mortgage Operations</a></article>
  <article class="service-card service-contract"><p class="service-number">03</p><h2>Contract and Commercial Operations</h2><p>Contract lifecycle and commercial process services covering intake, drafting from approved templates, review coordination, execution, repositories, obligations, amendments and commercial data.<span class="card-detail">Commercial data includes fees, pricing, rebates, sponsorship payments, commissions, revenue shares, escalation mechanisms, service credits and other agreed financial terms, together with the conditions that determine when they apply.</span></p><a href="$BasePath/services/contract-commercial-operations.html">Explore Contract Operations</a></article>
  <article class="service-card service-product"><p class="service-number">04</p><h2>Legal Tech and AI Quality Services</h2><p>Business-user testing and human validation of AI-extracted clauses, summaries, commercial fields and workflow outputs for legal, contract and property technology.</p><a href="$BasePath/services/legal-tech-ai-quality-services.html">Explore Quality Services</a></article>
  <article class="service-card service-legal"><p class="service-number">05</p><h2>Specialist Legal Process Services</h2><p>Legal and case-law research, drafting from approved templates and instructions, document review, due diligence, chronologies, matter administration, patent and prior-art research and structured reporting.</p><a href="$BasePath/services/specialist-legal-process-services.html">Explore Legal Process Services</a></article>
</div>
"@

$servicesMain = @"
<section class="page-hero editorial-hero">
  <div class="container narrow">
    <p class="eyebrow">Alternative legal and business process services</p>
    <h1>Services delivered as an extension of your team</h1>
    <p class="lead">Axentra works alongside law firms, in-house legal and business teams, lenders, servicers, and legal, contract and property technology companies.</p>
    <p>Clients engage Axentra for on-demand requirements, defined projects, managed recurring workflows, dedicated teams and secondments.</p>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="section-heading split-heading"><div><p class="eyebrow">Service areas</p><h2>Five specialist services</h2></div><p>Delivery is arranged around the scope, volumes, required experience, client systems, working hours, review layers and reporting requirements.</p></div>
    $serviceCards
  </div>
</section>
<section class="section section-muted">
  <div class="container compact-split">
    <div><p class="eyebrow">Workflow Assessment</p><h2>Define the right delivery structure</h2><p>Axentra reviews the work, volumes, systems, skills, review responsibilities and team coverage before proposing the team and transition plan.</p></div>
    <a class="button secondary" href="$BasePath/services/workflow-assessment.html">Explore Workflow Assessment</a>
  </div>
</section>
<section class="section section-dark">
  <div class="container connected-services">
    <div><p class="eyebrow">Related service areas</p><h2>Bankruptcy and mortgage work meet at specific case events</h2></div>
    <p>A borrower filing affects servicing activity, claims, payments, foreclosure records and loan-system updates. The bankruptcy and mortgage teams keep their own responsibilities and reporting while sharing the case and loan information needed for the work.</p>
  </div>
</section>
$(Get-ContactBand -Heading 'Explore the right delivery option for your team' -Copy 'Share the work type, volumes, duration, working hours, systems and experience you need.')
"@

Write-SiteFile -Path 'services/index.html' -Content (Get-Page -Title 'Legal and Business Process Services | Axentra' -Description 'Explore Axentra services across bankruptcy, mortgage servicing and default, contracts and commercial operations, legal tech and AI quality, and specialist legal processes.' -Canonical "$SiteUrl/services/" -Active 'services' -Main $servicesMain -BodyClass 'services-page')

# Bankruptcy Operations
$bankruptcyProcess = @('Pre-filing Operations','Calculations and Schedules','Filing Readiness','Post-filing Case Operations','Creditor, Lender and Servicer Operations')
$bankruptcyPrefiling = @('Matter intake','Client questionnaires','Document-request lists','Document collection and indexing','Income and expense information','Asset and liability information','Creditor details','Missing-information follow-up','Inconsistency and exception records','Data entry into client-approved bankruptcy software','Attorney-review package preparation')
$bankruptcyCalculations = @('Six-month income review','Current monthly income worksheets','Median-income comparison','Chapter 7 means-test preparation','Chapter 13 disposable-income preparation','Schedule I and Schedule J preparation and reconciliation','Secured-debt and arrears information','Asset, liability and equity worksheets','Plan-payment worksheet preparation under client instructions','Formula and source checks')
$bankruptcyFiling = @('Petition and schedule preparation','Statement preparation','Creditor matrix','Local forms','Filing-fee documents','Credit-counselling certificate','Signature tracking','Redaction checks','Cross-form checks','Missing-field review','Filing-package organisation','Attorney approval tracking')
$bankruptcyPostFiling = @('Filed-case setup','Court and case information','Docket monitoring','PACER monitoring','Deficiency tracking','Trustee document requests','Section 341 meeting tracking','Hearing and deadline tracking','Claims register monitoring','Proof-of-claim records','Amendments','Chapter 7 event tracking','Chapter 13 plan and payment tracking','Mortgage cure information','Motions and objections tracker','Discharge tracking','Dismissal, conversion and closure records','Final file organisation','Case-status reporting')
$bankruptcyCreditor = @('Bankruptcy-notice intake','Borrower and loan matching','Automatic-stay records','Proof-of-claim preparation','Principal, interest, escrow and arrears reconciliation','Payment-history review','Plan and confirmation-order abstraction','Pre-petition and post-petition payment tracking','Payment-change notice preparation','Post-petition fee and expense records','Final cure and payment records','Dismissal, discharge and closure updates')

$bankruptcyMain = @"
<section class="page-hero service-detail-hero"><div class="container narrow"><p class="eyebrow">Bankruptcy Operations</p><h1>Pre-filing and post-filing bankruptcy operations</h1><p class="lead">Pre-filing, calculation, filing-readiness and post-filing services for law firms, creditors, lenders and servicers.</p><p>Delivery is performed within the scope, systems, templates, instructions and legal-review arrangements agreed with the client.</p><a class="button primary" href="$BasePath/contact.html?service=bankruptcy">Discuss Bankruptcy Operations</a></div></section>
<section class="section process-section"><div class="container"><div class="section-heading"><p class="eyebrow">Bankruptcy operations</p><h2>Five parts of the service</h2></div>$(Get-ProcessMarkup -Items $bankruptcyProcess -Label 'Bankruptcy service areas')</div></section>
<section class="section section-muted"><div class="container detail-layout"><div class="section-intro"><p class="section-index">01</p><p class="eyebrow">Before filing</p><h2>Pre-filing operations</h2><p>The team organises the information and documents needed for attorney review and petition preparation.</p></div><div>$(Get-ScopePanel -Title 'Pre-filing activities' -Items $bankruptcyPrefiling -Open)</div></div></section>
<section class="section calculations-section"><div class="container detail-layout"><div class="section-intro"><p class="section-index">02</p><p class="eyebrow">Financial work</p><h2>Calculations and schedules</h2><p>Worksheets follow client instructions, current source information and the legal treatment provided by the responsible attorney.</p></div><div>$(Get-ScopePanel -Title 'Calculation and schedule activities' -Items $bankruptcyCalculations -Open)<p class="boundary-note compact-boundary">Legal conclusions, chapter selection, exemptions, claim treatment and filing approval remain within the client's authorised legal-review process.</p></div></div></section>
<section class="section section-muted"><div class="container detail-layout"><div class="section-intro"><p class="section-index">03</p><p class="eyebrow">Preparing the package</p><h2>Filing readiness</h2><p>Documents, forms and open items are brought together for the client's legal review and approval.</p></div><div>$(Get-ScopePanel -Title 'Filing-readiness activities' -Items $bankruptcyFiling -Open)</div></div></section>
<section class="section section-dark post-filing-section"><div class="container detail-layout"><div class="section-intro"><p class="section-index">04</p><p class="eyebrow">After filing</p><h2>Post-filing case operations</h2><p>Post-filing work covers court information, trustee requests, claims, hearings, payments, case events and closure records. Axentra tracks the action, deadline and status in the client's working environment.</p></div><div>$(Get-ScopePanel -Title 'Post-filing activities' -Items $bankruptcyPostFiling -Open)</div></div></section>
<section class="section"><div class="container detail-layout"><div class="section-intro"><p class="section-index">05</p><p class="eyebrow">Claims and loan records</p><h2>Creditor, lender and servicer operations</h2><p>The team matches the bankruptcy case with the borrower and loan record, prepares claim information and tracks payment and case updates. Legal strategy, pleading signature and court representation remain with the client's counsel.</p><a class="text-link" href="$BasePath/services/mortgage-servicing-default-operations.html">Explore Mortgage Servicing and Default Operations</a></div><div>$(Get-ScopePanel -Title 'Creditor, lender and servicer activities' -Items $bankruptcyCreditor -Open)</div></div></section>
$(Get-ContactBand -Eyebrow 'Bankruptcy operations' -Heading 'Discuss pre-filing, calculation or post-filing delivery' -Copy 'Tell us about the case stage, expected volumes, software, working hours and legal-review arrangement.')
"@

Write-SiteFile -Path 'services/bankruptcy-operations.html' -Content (Get-Page -Title 'Bankruptcy Operations | Axentra' -Description 'Bankruptcy operations covering pre-filing work, Chapter 7 and Chapter 13 calculations, filing readiness, post-filing cases, claims and creditor, lender and servicer records.' -Canonical "$SiteUrl/services/bankruptcy-operations.html" -Active 'services' -Main $bankruptcyMain -BodyClass 'service-detail-page bankruptcy-page')

# Mortgage Servicing and Default Operations
$mortgageProcess = @('Loan and Document Review','Account Reconciliation','Delinquency Operations','Loss-Mitigation Administration','Foreclosure Tracking','Bankruptcy Operations','Post-Foreclosure Records')
$mortgageOnboarding = @('Loan and borrower data review','Promissory note, mortgage and deed-of-trust records','Assignments, allonges and endorsements','Property and title-document information','Origination, modification and forbearance documents','Payment-history setup','Escrow, insurance and tax information','Missing-document and collateral-item trackers','Repository updates','Source-to-system checks')
$mortgageCalculations = @('Unpaid principal balance','Principal and interest breakdown','Interest-accrual and per-diem worksheets','Escrow balances, shortages and surpluses','Tax and insurance advances','Fees, expenses and corporate advances','Suspense and unapplied amounts','Delinquency amount','Pre-petition and post-petition arrears','Reinstatement and payoff information preparation','Payment-history reconciliation','Modification, forbearance and repayment-plan information','Investor reporting reconciliation')
$mortgageDelinquency = @('Delinquency status and missed-payment records','Days-past-due tracking','Borrower-contact activity records','Notice and communication trackers','Hardship and assistance-package information','Required-document lists','Incomplete-information follow-up','Escalation records','Property, insurance and tax updates','Specialist and counsel referral packages')
$mortgageLossMitigation = @('Assistance-package intake','Completeness checks against client checklists','Missing-document correspondence from client templates','Income, expense, hardship and property information','Document-expiry and version tracking','Evaluation inputs under client rules','Forbearance and repayment-plan administration','Modification-document and trial-payment tracking','Short-sale and deed-in-lieu documents','Response and appeal deadlines','Foreclosure-hold records','Quality review')
$mortgageForeclosure = @('Foreclosure referral package','Document review for referral','Note, mortgage, assignment and payment-history records','Default, acceleration, reinstatement and payoff information','Counsel instruction package','Referral and milestone tracking','Title-search and title-report administration','Title-item tracker','Service, publication, hearing and sale dates','Fee and cost records','Loss-mitigation and bankruptcy holds','Counsel status tracking','Post-sale document administration')
$mortgageBankruptcy = @('Bankruptcy notice','Borrower, loan and case matching','Chapter, filing date and automatic-stay records','Counsel referral','Proof-of-claim data and mortgage claim attachment','Principal, interest, escrow, arrears, fee and charge reconciliation','Payment history and claims bar date','Plan and confirmation-order abstraction','Pre-petition and post-petition payment records','Payment-change and post-petition fee notice preparation','Final cure and payment records','Dismissal, conversion, discharge and closure updates','Servicing-system and client reporting')
$mortgagePostForeclosure = @('Foreclosure-sale result','Title and vesting records','Possession and eviction milestone records','Property-preservation, insurance and tax records','Valuation and inspection records','Redemption-period tracking','Claim and recovery file','REO file records','Broker and property-manager document administration','Sale and closing documents','Expense and advance reconciliation','Final account reconciliation','File closure and retention records')

$mortgageMain = @"
<section class="page-hero service-detail-hero"><div class="container narrow"><p class="eyebrow">Mortgage Servicing and Default Operations</p><h1>Mortgage and default processes from loan records through closure</h1><p class="lead">Mortgage and default process services covering loan records, account reconciliation, delinquency, loss-mitigation administration, foreclosure tracking, bankruptcy and post-foreclosure records.</p><p>Delivery follows client servicing rules, investor requirements, systems, templates and decision paths. Axentra does not act as a lender, licensed mortgage servicer, debt collector, foreclosure counsel, title adviser, broker or asset manager.</p><a class="button primary" href="$BasePath/contact.html?service=mortgage">Discuss Mortgage Operations</a></div></section>
<section class="section process-section"><div class="container"><div class="section-heading"><p class="eyebrow">Mortgage service areas</p><h2>Services as the loan record changes</h2></div>$(Get-ProcessMarkup -Items $mortgageProcess -Label 'Mortgage servicing and default service areas')</div></section>
<section class="section section-muted"><div class="container"><div class="scope-grid">$(Get-ScopePanel -Title 'Loan and document review' -Items $mortgageOnboarding -Open)$(Get-ScopePanel -Title 'Account calculations and reconciliation' -Items $mortgageCalculations -Open)</div><p class="boundary-note compact-boundary">Calculations follow the client's servicing method, loan documents, investor requirements and review process. Axentra does not decide which amounts are legally recoverable from a borrower.</p></div></section>
<section class="section"><div class="container"><div class="scope-grid">$(Get-ScopePanel -Title 'Delinquency operations' -Items $mortgageDelinquency -Open)$(Get-ScopePanel -Title 'Loss-mitigation administration' -Items $mortgageLossMitigation -Open)</div><p class="boundary-note compact-boundary">Lending, credit, eligibility, investor and loss-mitigation decisions remain with the lender, servicer, investor or counsel.</p></div></section>
<section class="section section-dark"><div class="container"><div class="scope-grid">$(Get-ScopePanel -Title 'Foreclosure tracking' -Items $mortgageForeclosure -Open)$(Get-ScopePanel -Title 'Mortgage operations during bankruptcy' -Items $mortgageBankruptcy -Open)</div><p class="boundary-note dark-boundary">Axentra prepares document records, referrals and milestone trackers. It does not conduct foreclosure, provide legal strategy or sign pleadings.</p></div></section>
<section class="section section-muted"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">After foreclosure</p><h2>Post-foreclosure records</h2><p>Administration keeps property, expense, recovery and closure records together. Brokerage, property-management and title decisions remain with the responsible client or provider.</p></div><div>$(Get-ScopePanel -Title 'Post-foreclosure records' -Items $mortgagePostForeclosure -Open)</div></div></section>
$(Get-ContactBand -Eyebrow 'Mortgage operations' -Heading 'Discuss loan-record, default or bankruptcy delivery' -Copy 'Tell us about the portfolio stage, systems, volumes, working hours and reporting needed.')
"@

Write-SiteFile -Path 'services/mortgage-servicing-default-operations.html' -Content (Get-Page -Title 'Mortgage Servicing and Default Operations | Axentra' -Description 'Mortgage and default process services for loan documents, account reconciliation, delinquency, loss-mitigation administration, foreclosure, bankruptcy and post-foreclosure records.' -Canonical "$SiteUrl/services/mortgage-servicing-default-operations.html" -Active 'services' -Main $mortgageMain -BodyClass 'service-detail-page mortgage-page')

# Contract and Commercial Operations
$contractProcess = @('Business Request','Information and Documents','Draft and Review','Approvals and Signature','Repository','Obligations and Changes','Commercial Reporting')
$contractPre = @('Intake and request triage','Information and document checks','Drafting from approved templates','First-level review preparation','Clause comparison','Deviation identification','Redline and negotiation tracking','Approval coordination','Version control','Supporting-document checks')
$contractExecution = @('Final-version checks','Signature coordination','Execution-status tracking','Document collation','Filing','Repository preparation')
$contractPost = @('Repository administration','Metadata','Renewal and expiry tracking','Obligation and notice tracking','Amendment and variation tracking','Commercial-term tracking','Open-item management','Reporting','Data clean-up','Quality review')
$commercialTerms = @('Fees and pricing','Fixed and variable charges','Revenue shares and percentage rent','Minimum guarantees','Escalation and indexation','Sponsorship payments','Rebates and credits','Incentives and commissions','Discounts and service credits','Payment milestones','Caps, floors and thresholds','Renewal and termination pricing','Taxes and withholding','Audit and reconciliation rights')
$commercialLogic = @('Value','Trigger','Calculation basis','Threshold','Frequency','Effective period','Adjustment method','Dependency','Exception','Notice','Owner','Supporting record','Review status')
$commercialUses = @('Revenue and margin review','Billing preparation','Lease administration','Sponsorship management','Rebate and supplier-credit tracking','Fee reconciliation','Commercial reporting','Post-signature obligation management')

$contractMain = @"
<section class="page-hero service-detail-hero"><div class="container narrow"><p class="eyebrow">Contract and Commercial Operations</p><h1>Contract lifecycle and commercial process services</h1><p class="lead">Services cover contract intake, drafting from approved templates, review coordination, execution, repositories, obligations, amendments and commercial data.</p><p>Commercial data includes fees, pricing, rebates, sponsorship payments, commissions, revenue shares, escalation mechanisms, service credits and other agreed financial terms, together with the conditions that determine when they apply.</p><a class="button primary" href="$BasePath/contact.html?service=contracts">Discuss Contract Services</a></div></section>
<section class="section process-section"><div class="container"><div class="section-heading"><p class="eyebrow">Contract lifecycle</p><h2>From the business request to post-signature reporting</h2></div>$(Get-ProcessMarkup -Items $contractProcess -Label 'Contract and commercial service areas')</div></section>
<section class="section section-muted"><div class="container"><div class="scope-grid three-column">$(Get-ScopePanel -Title 'Before signature' -Items $contractPre -Open)$(Get-ScopePanel -Title 'Signature and execution' -Items $contractExecution -Open)$(Get-ScopePanel -Title 'After signature' -Items $contractPost -Open)</div></div></section>
<section class="section commercial-logic-section"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Commercial data</p><h2>A value is useful only when its conditions are clear</h2></div><p>Axentra records the financial term together with the event, period, calculation, dependency, notice and owner that determine how it applies.</p></div><div class="commercial-grid"><div class="commercial-panel"><h3>Financial terms</h3>$(Get-ListMarkup -Items $commercialTerms)</div><div class="commercial-panel logic-panel"><h3>Information recorded with the value</h3>$(Get-ListMarkup -Items $commercialLogic)</div></div></div></section>
<section class="section section-dark"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Business use</p><h2>Make contract data available to the teams that use it</h2><p>Legal, finance, procurement, property and commercial teams receive records that keep the term and its conditions together.</p></div><div>$(Get-ListMarkup -Items $commercialUses -ClassName 'output-list light-output')</div></div></section>
$(Get-ContactBand -Eyebrow 'Contract and commercial services' -Heading 'Discuss a contract or commercial-data project' -Copy 'Tell us about the contract type, volumes, templates, playbook, repository and reporting needed.')
"@

Write-SiteFile -Path 'services/contract-commercial-operations.html' -Content (Get-Page -Title 'Contract and Commercial Operations | Axentra' -Description 'Contract lifecycle and commercial process services across intake, approved-template drafting, review, execution, repositories, obligations, amendments and financial data.' -Canonical "$SiteUrl/services/contract-commercial-operations.html" -Active 'services' -Main $contractMain -BodyClass 'service-detail-page contract-page')

# Legal Tech and AI Quality Services
$businessUserTesting = @('Agreed user journeys','Document upload','Data fields','Workflow routing','Approvals','Alerts and reminders','User-facing reports','Issue records','Retesting after corrections')
$aiClauseValidation = @('Correct clause or field','Correct extracted value','Missing information','Incorrect classification','Conditions and qualifications','Exceptions','Amendments','Source references','Commercial dependencies')
$errorTrendItems = @('Fields that repeatedly fail','Clauses that need frequent correction','Document types with recurring issues','Wording patterns linked to errors','Areas requiring high levels of manual review','Retesting after updates')

$legalTechMain = @"
<section class="page-hero service-detail-hero"><div class="container narrow"><p class="eyebrow">Legal Tech and AI Quality Services</p><h1>Business-user testing and human validation for legal technology</h1><p class="lead">Axentra tests whether legal, contract and property technology operates as expected and validates AI-generated information against source documents.</p><p>The service covers business-user testing, AI clause and data validation, summary validation, error trends and retesting. It is not a complete software QA or engineering service.</p><a class="button primary" href="$BasePath/contact.html?service=legal-tech-ai">Discuss Quality Services</a></div></section>
<section class="section section-muted"><div class="container detail-layout"><div class="section-intro"><p class="section-index">01</p><p class="eyebrow">Business-user testing</p><h2>Test the product through the user's work</h2><p>Axentra tests whether a configured product or workflow operates as expected for the legal, contract, property or business user.</p><p>This form of business-user testing is commonly known as user acceptance testing, or UAT.</p><p>It does not include source-code, penetration, performance or cybersecurity testing.</p></div><div>$(Get-ScopePanel -Title 'Business-user testing activities' -Items $businessUserTesting -Open)</div></div></section>
<section class="section"><div class="container detail-layout"><div class="section-intro"><p class="section-index">02</p><p class="eyebrow">AI clause and data validation</p><h2>Compare extracted information with the source</h2><p>Axentra compares AI-extracted clauses and data fields with the source document.</p></div><div>$(Get-ScopePanel -Title 'Clause and data review' -Items $aiClauseValidation -Open)</div></div></section>
<section class="section section-muted"><div class="container narrow"><p class="section-index">03</p><p class="eyebrow">AI summary validation</p><h2>Check that the summary keeps the important detail</h2><p class="lead">Axentra reviews whether a generated summary accurately reflects the source document and preserves relevant conditions, qualifications, dates, amounts and party responsibilities.</p></div></section>
<section class="section section-dark"><div class="container detail-layout"><div class="section-intro"><p class="section-index">04</p><p class="eyebrow">Error trends and retesting</p><h2>Group repeated corrections and share what they show</h2><p>Individual corrections are grouped to identify which clauses, fields, document types or wording patterns continue to produce errors or require high levels of manual review.</p><p>Axentra shares these findings with the client's legal, product or data team to inform changes to extraction rules, prompts, playbooks, user instructions and test examples.</p><p>Updated outputs are retested against the agreed source documents and validation criteria.</p><p>Axentra does not train or retrain AI models, develop AI software, change source code or own product-release decisions.</p></div><div>$(Get-ScopePanel -Title 'Trend and retesting activities' -Items $errorTrendItems -Open)</div></div></section>
$(Get-ContactBand -Eyebrow 'Legal Tech and AI Quality Services' -Heading 'Discuss business-user testing or AI validation' -Copy 'Tell us about the product, intended users, source documents, outputs and recurring issues you want reviewed.')
"@

Write-SiteFile -Path 'services/legal-tech-ai-quality-services.html' -Content (Get-Page -Title 'Legal Tech and AI Quality Services | Axentra' -Description 'Business-user testing and human validation of AI-extracted clauses, summaries, commercial fields and workflow outputs for legal, contract and property technology.' -Canonical "$SiteUrl/services/legal-tech-ai-quality-services.html" -Active 'services' -Main $legalTechMain -BodyClass 'service-detail-page product-page')

# Specialist Legal Process Services
$definedLegalScope = @('Legal research','Case-law research','Research summaries','Chronologies','Drafting from approved templates and instructions','Document review and classification','Due diligence','Matter administration','Evidence indexing','Regulatory and public-record research','Patent research','Prior-art research','Structured legal reporting')
$definedAssignment = @('Question and jurisdiction','Expected sources','Information available','Information unavailable','Assumptions','Output and citation needs','Client review responsibility','Open issues','Completion status')

$definedLegalMain = @"
<section class="page-hero service-detail-hero"><div class="container narrow"><p class="eyebrow">Specialist Legal Process Services</p><h1>Specialist legal processes for defined assignments</h1><p class="lead">Legal and case-law research, drafting from approved templates and instructions, document review, due diligence, chronologies, matter administration, patent and prior-art research and structured reporting.</p><p>Each assignment identifies the question, jurisdiction, available information, expected sources, output and client review responsibility.</p><a class="button primary" href="$BasePath/contact.html?service=specialist-legal">Discuss Legal Process Services</a></div></section>
<section class="section section-muted"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Service activities</p><h2>Research, documents and matter services</h2><p>Patent services are limited to research and prior-art work. The service does not include patent prosecution or patentability opinions.</p></div><div>$(Get-ScopePanel -Title 'Specialist legal process activities' -Items $definedLegalScope -Open)</div></div></section>
<section class="section"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Assignment brief</p><h2>Start with a clear question and output</h2><p>The brief records what the team will use, what it will produce and which questions remain for the client.</p></div><div>$(Get-ListMarkup -Items $definedAssignment -ClassName 'output-list')</div></div></section>
$(Get-ContactBand -Eyebrow 'Specialist legal processes' -Heading 'Discuss a legal research or document project' -Copy 'Tell us about the question, jurisdiction, source material, timeline and output you need.')
"@

Write-SiteFile -Path 'services/specialist-legal-process-services.html' -Content (Get-Page -Title 'Specialist Legal Process Services | Axentra' -Description 'Specialist legal process services for research, approved-template drafting, document review, chronologies, due diligence, matter administration, patent and prior-art research.' -Canonical "$SiteUrl/services/specialist-legal-process-services.html" -Active 'services' -Main $definedLegalMain -BodyClass 'service-detail-page legal-process-page')

# Workflow Assessment
$assessmentQuestions = @('What starts the work?','What information and documents are needed?','Which decisions stay with the client?','Which activities move to the Axentra team?','What systems and access are involved?','What interrupts the ordinary process?','What confirms that the work is complete?')
$assessmentOutputs = @('Scope map','Responsibility map','Information and access map','Process flow','Client review points','Quality checks','Common issues','Team and skill needs','Reporting measures','Transition dependencies','Pilot recommendation')

$assessmentMain = @"
<section class="page-hero service-detail-hero"><div class="container narrow"><p class="eyebrow">Workflow Assessment</p><h1>Understand the work before proposing the team</h1><p class="lead">Axentra reviews the work, volumes, information, systems, skills, working hours, client decisions and quality checks before proposing a delivery structure.</p><p>The assessment helps both teams agree what will move, what stays with the client and what is needed for a practical transition.</p><a class="button primary" href="$BasePath/contact.html?service=assessment">Discuss Your Requirement</a></div></section>
<section class="section section-muted"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Assessment questions</p><h2>Seven questions that clarify the work</h2><p>Design-thinking methods are used where they help the teams understand users, handoffs and recurring problems. The approach depends on the project.</p></div><ol class="assessment-questions">$(for ($i = 0; $i -lt $assessmentQuestions.Count; $i++) { '<li><span>{0:D2}</span><strong>{1}</strong></li>' -f ($i + 1), $assessmentQuestions[$i] })</ol></div></section>
<section class="section"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Typical outputs</p><h2>A practical basis for scope, staffing and transition</h2><p>Open questions and dependencies are documented before work moves to the delivery team.</p></div><div>$(Get-ListMarkup -Items $assessmentOutputs -ClassName 'output-list')</div></div></section>
$(Get-ContactBand -Eyebrow 'Workflow assessment' -Heading 'Discuss the work and delivery structure you are considering' -Copy 'Start with the work type, current team, volumes, systems, working hours and points that need attention.')
"@

Write-SiteFile -Path 'services/workflow-assessment.html' -Content (Get-Page -Title 'Workflow Assessment | Axentra' -Description 'Axentra reviews work, volumes, information, systems, responsibilities, skills, working hours, quality checks and transition needs before proposing a delivery structure.' -Canonical "$SiteUrl/services/workflow-assessment.html" -Active 'services' -Main $assessmentMain -BodyClass 'service-detail-page assessment-page')
