$homeSchema = @"
    <script type="application/ld+json">
      {"@context":"https://schema.org","@type":"Organization","name":"Axentra Solutions Pvt. Ltd.","url":"$SiteUrl/","logo":"$SiteUrl/assets/images/axentra-solutions-logo.jpeg","email":"$GeneralEmail","telephone":"+91 97250 24355","description":"Alternative legal and business process services for clients in India and international markets.","sameAs":["$LinkedInUrl"]}
    </script>
"@

$homeMain = @"
<section class="home-hero">
  <img class="home-hero-image" src="$BasePath/assets/axentra-operations-visual.jpg" alt="Legal and business process teams reviewing documents and workflow information" width="1774" height="887" fetchpriority="high" />
  <div class="home-hero-overlay" aria-hidden="true"></div>
  <div class="container home-hero-content">
    <p class="eyebrow">Alternative legal and business process services</p>
    <h1>Legal and business process support built around your workload</h1>
    <div class="home-hero-copy">
      <p>Axentra supports law firms, in-house teams, lenders, servicers and legal, contract and property technology businesses in India and international markets.</p>
      <p>We provide on-demand and project support, managed workflows for recurring requirements, dedicated delivery teams and seconded professionals working within client teams.</p>
      <p>Our services cover bankruptcy pre-filing and post-filing operations, mortgage servicing and default support, contract and commercial operations, defined legal support, and legal-tech and AI quality review.</p>
    </div>
    <div class="button-row"><a class="button primary" href="$BasePath/services/">Explore Services</a><a class="button secondary" href="$BasePath/contact.html">Discuss Your Requirement</a></div>
    <ul class="hero-support-strip" aria-label="Delivery options"><li>India-based delivery</li><li>Time-zone-aligned coverage</li><li>Planned holiday and peak-volume support</li><li>Client and approved-system delivery</li></ul>
  </div>
</section>
<section class="section home-services"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Primary services</p><h2>Support across legal and business operations</h2></div><p>Choose a service area to see the activities Axentra supports, the role of the client team and the information needed to begin.</p></div>$serviceCards</div></section>
<section class="section section-muted engagement-section"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">How clients engage us</p><h2>Support structured around the requirement</h2></div><p>The delivery structure depends on the work, volumes, duration, required experience, systems, review requirements and client working hours.</p></div><div class="engagement-grid"><article><h3>On-demand support</h3><p>Additional capacity for backlog, workload peaks, urgent deadlines, team leave or temporary resource gaps.</p></article><article><h3>Defined projects</h3><p>A team and delivery plan arranged around a specific scope, output, timeline and completion criteria.</p></article><article><h3>Managed workflows</h3><p>Ongoing support for recurring work with agreed instructions, service levels, quality checks, reporting and escalation routes.</p></article><article><h3>Dedicated teams</h3><p>Teams structured according to the required roles, experience, volumes, quality layers, supervision and time-zone coverage.</p></article><article><h3>Secondments</h3><p>Professionals assigned for an agreed period to work within the client's team, systems, instructions, reporting structure and business hours.</p></article></div></div></section>
<section class="section coverage-section"><div class="container coverage-grid"><div><p class="eyebrow">India and international delivery</p><h2>Supporting clients across markets and time zones</h2></div><div><p>Axentra delivers from India for clients in India and international markets.</p><p>Working hours and team coverage are agreed according to the client's location, business hours, deadlines and workflow requirements. This may include scheduled overlap with client teams, early or late working windows and planned coverage during client or local holidays.</p><p>Holiday and extended-hour coverage is arranged in advance through the engagement staffing plan.</p></div></div></section>
<section class="section section-dark assessment-cta"><div class="container compact-split"><div><p class="eyebrow">Workflow Assessment</p><h2>Start by reviewing the work and the support it needs</h2><p>Axentra can assess volumes, systems, skills, review responsibilities and working hours before proposing a delivery approach.</p></div><a class="button secondary" href="$BasePath/services/workflow-assessment.html">Explore Workflow Assessment</a></div></section>
"@

Write-SiteFile -Path 'index.html' -Content (Get-Page -Title 'Axentra | Alternative Legal and Business Process Services' -Description 'Axentra provides alternative legal and business process services from India for law firms, in-house teams, lenders, servicers and technology businesses.' -Canonical "$SiteUrl/" -Active 'home' -Main $homeMain -BodyClass 'home-page' -AdditionalHead $homeSchema)

# How We Work
$managedProcess = @('Understand','Set up','Transition','Deliver','Review')
$teamFactors = @('Work type','Expected volumes','Required legal or business knowledge','Turnaround requirements','Client working hours','Production and review responsibilities','Quality-control requirements','Reporting and escalation needs','Project duration','Required systems and access')
$teamRoles = @('Analysts','Paralegals','Lawyers','Legal or business process specialists','Quality reviewers','Team leads','Delivery managers','Subject-matter support')

$howMain = @"
<section class="page-hero editorial-hero"><div class="container narrow"><p class="eyebrow">How we work</p><h1>Delivery starts with understanding the work</h1><p class="lead">Axentra reviews the work, people, systems, deadlines and expected output before proposing the team and delivery plan.</p><p>Where useful for the project, design-thinking methods help uncover user needs, dependencies and friction before solutions are proposed. Client feedback continues after work begins, so instructions, training and delivery can be adjusted throughout the engagement.</p><a class="button primary" href="$BasePath/contact.html">Discuss Your Requirement</a></div></section>
<section class="section process-section"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Company-wide process</p><h2>Five steps from discussion to ongoing review</h2></div><p>The same core process applies across projects, recurring workflows, dedicated teams and secondments.</p></div>$(Get-ProcessMarkup -Items $managedProcess -Label 'Axentra delivery process')</div></section>
<section class="section section-muted"><div class="container"><div class="delivery-stage-grid"><article><p class="section-index">01</p><h3>Understand</h3><p>Review the work, volumes, systems, deadlines, data and expected output.</p></article><article><p class="section-index">02</p><h3>Set up</h3><p>Agree the team, roles, instructions, access, quality checks, reporting and escalation routes.</p></article><article><p class="section-index">03</p><h3>Transition</h3><p>Complete knowledge transfer, training, system access, sample work and initial quality review.</p></article><article><p class="section-index">04</p><h3>Deliver</h3><p>Perform and review the work, track open items and report status under the agreed service structure.</p></article><article><p class="section-index">05</p><h3>Review</h3><p>Use quality findings, client feedback and recurring issues to improve instructions, training and delivery.</p></article></div></div></section>
<section class="section team-section"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Engagement-specific teams</p><h2>The team follows the work</h2></div><div><p>Axentra does not apply one fixed team structure to every engagement.</p><p>The team is arranged around the work and the client's delivery needs.</p></div></div><div class="team-grid"><div><h3>What shapes the team</h3>$(Get-ListMarkup -Items $teamFactors -ClassName 'output-list')</div><div><h3>Roles may include</h3>$(Get-ListMarkup -Items $teamRoles -ClassName 'output-list')</div></div></div></section>
$(Get-ContactBand -Heading 'Discuss the work, team and coverage you need' -Copy 'Share the work type, volumes, systems, working hours, duration and review responsibilities.')
"@

Write-SiteFile -Path 'how-we-work.html' -Content (Get-Page -Title 'How We Work | Axentra' -Description 'See how Axentra understands, sets up, transitions, delivers and reviews legal and business process support with teams arranged around each engagement.' -Canonical "$SiteUrl/how-we-work.html" -Active 'work' -Main $howMain -BodyClass 'how-page')

# Security and Trust
$peopleControls = @('Confidentiality and data-protection obligations','Intellectual-property and information-security obligations','Acceptable-use and AI-use rules','Training and policy acknowledgement','Continuing confidentiality after employment ends','Client-specific instructions')
$vendorControls = @('Confidentiality and data protection','Information security and access restrictions','AI use and incident reporting','Return or deletion of information','Restrictions on further subcontracting')
$policyAreas = @('Information security','Confidentiality and data handling','Privacy','Acceptable IT use','Remote working','Password and access management','AI use','Incident reporting','Retention and deletion','Vendor access')
$informationCategories = @('Confidential information','Personal data','Sensitive personal data','Protected health information','Intellectual property','Commercially sensitive information','Privileged material','Restricted records')
$responsibleAi = @('Client instructions and contract restrictions','Tools permitted for the engagement','Access controls and minimum necessary data','Human review','Vendor obligations','Escalation procedures')

$securityMain = @"
<section class="page-hero editorial-hero"><div class="container narrow"><p class="eyebrow">Security &amp; Trust</p><h1>How Axentra protects client information</h1><p class="lead">Security responsibilities are addressed through employment and vendor obligations, internal policies, workforce training, approved devices, system-access controls and engagement-specific data-handling requirements.</p><p>The safeguards used for an engagement depend on the information, client systems, contract terms and work being performed.</p></div></section>
<section class="section section-muted"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Employment and vendor obligations</p><h2>Responsibilities apply to the people and providers involved</h2></div><p>Personnel and relevant vendors receive confidentiality, security and data-handling responsibilities before they receive access needed for the work.</p></div><div class="scope-grid">$(Get-ScopePanel -Title 'Employment obligations' -Items $peopleControls -Open)$(Get-ScopePanel -Title 'Vendor obligations' -Items $vendorControls -Open)</div></div></section>
<section class="section"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Policies and training</p><h2>Clear instructions for handling client information</h2><p>Personnel acknowledge relevant policies, complete workforce training and receive any engagement-specific instructions before delivery begins.</p></div><div>$(Get-ListMarkup -Items $policyAreas -ClassName 'output-list')</div></div></section>
<section class="section section-dark"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">IT assets and access</p><h2>Access is limited to the work assigned</h2></div><p>Devices, user accounts, permitted software and remote-working arrangements are set for the engagement. Access is changed or removed when a role or assignment ends.</p></div><div class="guardrail-grid"><article><h3>Before access</h3><p>Confirm the device, user role, permitted systems and client restrictions.</p></article><article><h3>During delivery</h3><p>Use the assigned access and follow the engagement's download, storage, software and remote-working rules.</p></article><article><h3>When access changes</h3><p>Remove or update access, return assets and complete the required information-return or deletion steps.</p></article></div></div></section>
<section class="section"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Information handled</p><h2>Safeguards reflect the information involved</h2><p>Axentra identifies the types of information involved and follows the client, legal and contract terms that apply to their handling.</p></div><div>$(Get-ListMarkup -Items $informationCategories -ClassName 'output-list')</div></div></section>
<section class="section section-muted"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">AI use</p><h2>Use is limited by client instructions and engagement terms</h2></div><p class="statement">Client information is not entered into unauthorised public AI tools or used by Axentra for independent model training.</p></div>$(Get-ListMarkup -Items $responsibleAi -ClassName 'output-list')</div></section>
<section class="section"><div class="container security-response-grid"><article><p class="eyebrow">Incident response</p><h2>Report, contain and respond</h2><p>Personnel report suspected incidents through an internal escalation route. Response actions may include containment, access changes, record preservation, client notification, corrective action and recovery, according to the engagement terms.</p></article><article><p class="eyebrow">Business continuity</p><h2>Plan for interruptions</h2><p>Staffing, access, communication and recovery arrangements are considered during setup. Continuity steps are aligned with the work and the client's priorities.</p></article></div></section>
<section class="section section-dark"><div class="container trust-grid"><article><p class="eyebrow">PHI and HIPAA-related engagements</p><h2>Confirm roles before processing</h2><p>Where work involves protected health information, the parties address permitted use, safeguards, access, incident duties and any Business Associate Agreement before processing begins. Axentra does not describe itself as HIPAA certified.</p></article><article><p class="eyebrow">Certification position</p><h2>Claims reflect the current position</h2><p>Axentra does not claim an information-security or privacy certification it has not obtained. Relevant policies, practices and available supporting information can be discussed during client diligence.</p></article></div></section>
$(Get-ContactBand -Eyebrow 'Client diligence' -Heading 'Discuss security and data-handling requirements' -Copy 'Clients can review the information involved, access arrangements, contract terms and available supporting material before the engagement begins.')
"@

Write-SiteFile -Path 'security-trust.html' -Content (Get-Page -Title 'Security and Trust | Axentra' -Description 'How Axentra addresses employment and vendor obligations, policies, training, device and system access, AI use, incidents, continuity and client diligence.' -Canonical "$SiteUrl/security-trust.html" -Active 'security' -Main $securityMain -BodyClass 'security-page')

# About
$aboutPrinciples = @('Understand the requirement before proposing the team','Be clear about scope, responsibility and escalation','Protect client information','Maintain quality through review and feedback','Use technology responsibly','Adapt team structure and coverage to the engagement')

$aboutMain = @"
<section class="page-hero editorial-hero"><div class="container narrow"><p class="eyebrow">Company</p><h1>About Axentra</h1><p class="lead">Axentra is an alternative legal and business process services company supporting clients in India and international markets.</p><p>We provide additional capacity for defined projects, changing workloads and ongoing operations. Delivery is arranged through on-demand support, dedicated teams, managed workflows and seconded professionals working within client teams.</p><p>Our current service areas include bankruptcy, mortgage servicing and default support, contract and commercial operations, defined legal support, and legal-tech and AI quality review.</p></div></section>
<section class="section section-muted"><div class="container purpose-grid"><article><p class="eyebrow">Vision</p><h2>A dependable service company</h2><p>To build a dependable legal and business process services company known for clear communication, secure delivery and consistent quality.</p></article><article><p class="eyebrow">Mission</p><h2>Flexible support for changing needs</h2><p>To provide clients with trained teams and flexible delivery models for projects, recurring workflows and changing business needs.</p></article></div></section>
<section class="section"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">How we work</p><h2>Clear commitments carried into delivery</h2><p>Team structure, working hours and review responsibilities are arranged for the engagement.</p></div><div>$(Get-ListMarkup -Items $aboutPrinciples -ClassName 'output-list')</div></div></section>
<section class="section section-dark" id="leadership"><div class="container"><div class="section-heading"><p class="eyebrow">Leadership</p><h2>Company direction and service design</h2></div><div class="leader-grid"><article><p class="role">Founder</p><h3>Gagan Prajapati</h3><p>Gagan Prajapati is the Founder of Axentra Solutions. He works on company direction, partnerships and governance, while client delivery is managed through Axentra's service and operations teams.</p><a class="text-link light-link" href="https://www.linkedin.com/in/gagan-prajapati-6b3439a5/" target="_blank" rel="noopener noreferrer">Gagan on LinkedIn</a></article><article><p class="role">Co-founder</p><h3>Pooja Gore</h3><p>Pooja Gore is Co-founder of Axentra Solutions. She contributes to business development, client engagement and service models shaped around each client's workflows, systems and operating requirements.</p><a class="text-link light-link" href="https://www.linkedin.com/in/pooja-gore-99712723b/" target="_blank" rel="noopener noreferrer">Pooja on LinkedIn</a></article></div></div></section>
$(Get-ContactBand -Heading 'Discuss your requirement with Axentra' -Copy 'Share the work, duration, expected volumes, systems, working hours and team support you need.')
"@

Write-SiteFile -Path 'about.html' -Content (Get-Page -Title 'About Axentra' -Description 'Axentra is an alternative legal and business process services company supporting clients in India and international markets.' -Canonical "$SiteUrl/about.html" -Active 'about' -Main $aboutMain -BodyClass 'about-page')

# Insights
$insightCategories = @('Bankruptcy operations','Mortgage servicing and default operations','Contract and commercial operations','Legal tech and AI quality','Legal operations','Quality and workflow review','Information security','Commercial contract data')
$categoryMarkup = ($insightCategories | ForEach-Object { "<li>$_</li>" }) -join "`n"
$insightsMain = @"
<section class="page-hero editorial-hero"><div class="container narrow"><p class="eyebrow">Insights</p><h1>Practical questions behind legal and business process work</h1><p class="lead">Published observations on bankruptcy, mortgage, contracts, legal technology, service quality and information security.</p><a class="button secondary" href="$LinkedInUrl" target="_blank" rel="noopener noreferrer">Follow Axentra on LinkedIn</a></div></section>
<section class="section section-muted"><div class="container"><div class="section-heading"><p class="eyebrow">Topics</p><h2>Insight categories</h2></div><ul class="category-list" aria-label="Insight categories">$categoryMarkup</ul></div></section>
<section class="section"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Published posts</p><h2>Read from the source</h2></div><p>Only articles and LinkedIn posts already published by Axentra are linked here.</p></div><div class="insight-grid"><article class="insight-card"><div class="insight-tags"><span>Legal operations</span><span>Quality and workflow review</span></div><h3>Operational design for scalable business operations</h3><p>How clear workflows, ownership and quality review support dependable delivery.</p><a href="https://www.linkedin.com/posts/axentra-solutions-pvt-ltd_axentrasolutions-alsp-legaloperations-activity-7459630423296479233-0-J5" target="_blank" rel="noopener noreferrer">Read on LinkedIn</a></article><article class="insight-card"><div class="insight-tags"><span>Contract operations</span><span>Commercial contract data</span></div><h3>Vendor contract review: from clauses to operations</h3><p>How contract review connects approved language with later commercial activity.</p><a href="https://www.linkedin.com/posts/axentra-solutions-pvt-ltd_vendor-contract-review-from-clauses-to-operations-activity-7475593440907653120-kHWk" target="_blank" rel="noopener noreferrer">Read on LinkedIn</a></article></div></div></section>
<section class="section insight-faq-link"><div class="container compact-split"><div><p class="eyebrow">Looking for a direct answer?</p><h2>Service and operating questions are kept in a separate FAQ library</h2></div><a class="button secondary" href="$BasePath/faqs.html">Browse FAQs</a></div></section>
"@

Write-SiteFile -Path 'insights/index.html' -Content (Get-Page -Title 'Insights | Axentra' -Description 'Axentra insights on bankruptcy, mortgage, contract and commercial operations, legal tech and AI quality, legal operations and information security.' -Canonical "$SiteUrl/insights/" -Active 'insights' -Main $insightsMain -BodyClass 'insights-page')

# Contact
$contactMain = @"
<section class="page-hero editorial-hero"><div class="container narrow"><p class="eyebrow">Contact Axentra</p><h1>Discuss your requirement</h1><p class="lead">Tell us about the work, expected volumes, duration, systems, working hours and type of team support you are considering.</p><div class="contact-direct"><a href="mailto:$GeneralEmail">$GeneralEmail</a><a href="tel:+919725024355">+91 97250 24355</a><a href="$LinkedInUrl" target="_blank" rel="noopener noreferrer">Axentra on LinkedIn</a></div></div></section>
<section class="section"><div class="container contact-layout"><div class="contact-form-intro"><p class="eyebrow">Enquiry</p><h2>Share enough information for a useful first discussion</h2><p>The form prepares an email in your email application. The website does not transmit or store the entries.</p><p class="form-warning">Do not submit confidential information, personal data, protected health information, borrower records, case documents, loan documents or client files through this form. Secure information-transfer arrangements are established separately.</p></div><form class="contact-form" id="contact-form" novalidate><div class="form-row"><label for="contact-name">Name</label><input id="contact-name" name="name" autocomplete="name" required /></div><div class="form-row"><label for="contact-organisation">Organisation</label><input id="contact-organisation" name="organisation" autocomplete="organization" required /></div><div class="form-row"><label for="contact-email">Work email</label><input id="contact-email" name="email" type="email" autocomplete="email" required /></div><div class="form-row"><label for="contact-country">Country or market</label><input id="contact-country" name="country_market" autocomplete="country-name" required /></div><div class="form-row"><label for="contact-service">Service required</label><select id="contact-service" name="service" required><option value="">Select a service</option><option>Bankruptcy Operations</option><option>Mortgage Servicing and Default Operations</option><option>Contract and Commercial Operations</option><option>Legal Tech and AI Quality Support</option><option>Defined Legal Support</option><option>Workflow Assessment</option><option>Other</option></select></div><div class="form-row"><label for="contact-support-type">Type of support</label><select id="contact-support-type" name="support_type" required><option value="">Select a type</option><option>On-demand support</option><option>Defined project</option><option>Managed recurring workflow</option><option>Dedicated team</option><option>Secondment</option><option>Not yet decided</option></select></div><div class="form-row"><label for="contact-volume">Approximate volume or team requirement</label><input id="contact-volume" name="volume" /></div><div class="form-row"><label for="contact-hours">Preferred working hours or time-zone coverage</label><input id="contact-hours" name="working_hours" /></div><div class="form-row"><label for="contact-duration">Expected duration</label><input id="contact-duration" name="duration" /></div><div class="form-row full"><label for="contact-description">Brief description</label><textarea id="contact-description" name="description" rows="5" required></textarea></div><div class="form-actions full"><button class="button primary" type="submit">Prepare Email</button><p class="form-status" id="form-status" role="status" aria-live="polite"></p></div></form></div></section>
"@

Write-SiteFile -Path 'contact.html' -Content (Get-Page -Title 'Contact Axentra' -Description 'Contact Axentra to discuss legal and business process support, projects, managed workflows, dedicated teams or secondments.' -Canonical "$SiteUrl/contact.html" -Active 'contact' -Main $contactMain -BodyClass 'contact-page')

# Legal Notice
$legalMain = @"
<section class="page-hero policy-hero"><div class="container narrow"><p class="eyebrow">Legal Notice</p><h1>Website and service boundaries</h1><p>Clear terms for use of this website and the role Axentra describes on it.</p></div></section>
<section class="section"><div class="container policy-content"><h2>Axentra's role</h2><p>Axentra Solutions Pvt. Ltd. is not a law firm and does not provide legal representation. Use of this website, submission of an enquiry or communication with Axentra does not create a lawyer-client relationship.</p><p>Website information is general and is not legal, financial, lending, servicing, tax or other professional advice.</p><h2>Mortgage and bankruptcy boundaries</h2><p>Axentra does not act as a lender, licensed mortgage servicer, foreclosure counsel or debt collector unless a role is separately authorised and all applicable requirements are confirmed. Operational support remains within client-approved systems, instructions, decisions and review.</p><h2>Website use</h2><p>Use the website lawfully and do not attempt to interfere with its availability, security or content. Do not send client files or sensitive records through general website or email channels unless a secure transfer arrangement has been established.</p><h2>Intellectual property</h2><p>Website content, branding and original materials belong to Axentra or the relevant owner. They must not be represented as another party's work or reused in a misleading manner.</p><h2>External links</h2><p>External links are provided for reference. A link does not imply endorsement, control or responsibility for the external service or its content.</p><h2>Contact</h2><p>Questions about this notice may be sent to <a href="mailto:$GeneralEmail">$GeneralEmail</a>.</p></div></section>
"@

Write-SiteFile -Path 'legal-notice.html' -Content (Get-Page -Title 'Legal Notice | Axentra' -Description 'Axentra legal notice covering website use, service boundaries, no lawyer-client relationship, intellectual property, external links and contact information.' -Canonical "$SiteUrl/legal-notice.html" -Active '' -Main $legalMain -BodyClass 'policy-page')

# Privacy Notice
$privacyMain = @"
<section class="page-hero policy-hero"><div class="container narrow"><p class="eyebrow">Privacy Notice</p><h1>Website enquiries and information handling</h1><p>This notice describes information handled through the public Axentra website and general contact routes.</p></div></section>
<section class="section"><div class="container policy-content"><h2>Information provided by you</h2><p>The contact form prepares an email in your own email application. The website does not transmit or store the fields. If you send the email, Axentra receives the name, organisation, work email, country or market, service, type of support, approximate volume or team requirement, preferred working hours, expected duration and description you choose to include.</p><p>Axentra also receives information sent directly to its published email addresses or LinkedIn account.</p><h2>Purpose</h2><p>Enquiry information is used to respond, understand the stated requirement, arrange a discussion, maintain relevant correspondence and meet legal or security obligations.</p><h2>Technical information and analytics</h2><p>The website code does not use analytics, advertising trackers, account profiles or tracking cookies. It does not set optional cookies. GitHub Pages hosts the website and may process standard technical request information under its own terms.</p><h2>Storage, access and service providers</h2><p>Information sent by email is stored in the applicable email environment and accessed by personnel involved in responding to the enquiry, subject to organisational and provider controls. Hosting and communication providers process information only for the services they provide.</p><h2>Retention</h2><p>Enquiry records are retained only for a relevant business, security, contractual or legal purpose, then deleted or retained under the applicable record requirement.</p><h2>Your choices and rights</h2><p>You may ask Axentra to access, correct or delete enquiry information, or raise a privacy question. Applicable rights depend on the information and governing law.</p><h2>Contact</h2><p>Send privacy requests to <a href="mailto:$GeneralEmail">$GeneralEmail</a>. Do not include sensitive case, borrower, health, loan or client records in the first message.</p></div></section>
"@

Write-SiteFile -Path 'privacy-notice.html' -Content (Get-Page -Title 'Privacy Notice | Axentra' -Description 'Axentra website privacy notice covering contact-form and email enquiries, technical information, analytics, storage, access, retention, providers and user rights.' -Canonical "$SiteUrl/privacy-notice.html" -Active '' -Main $privacyMain -BodyClass 'policy-page')

# Accessibility
$accessibilityMain = @"
<section class="page-hero policy-hero"><div class="container narrow"><p class="eyebrow">Accessibility</p><h1>Access to Axentra's website</h1><p>The website is designed for keyboard use, readable contrast, responsive layouts and clear content structure.</p></div></section>
<section class="section"><div class="container policy-content"><h2>Accessibility measures</h2><p>Pages use semantic headings and landmarks, visible keyboard focus, a skip link, text alternatives for meaningful images, labelled form controls and process lists that remain readable without visual connectors.</p><h2>Responsive use</h2><p>Navigation, service scopes, process steps and contact fields adapt for desktop, tablet and mobile screens. Motion is limited and disabled where a user requests reduced motion.</p><h2>Feedback</h2><p>If any page, control or document is difficult to use, email <a href="mailto:$GeneralEmail">$GeneralEmail</a> with the page address and a short description of the problem.</p></div></section>
"@

Write-SiteFile -Path 'accessibility.html' -Content (Get-Page -Title 'Accessibility | Axentra' -Description 'Accessibility information for the Axentra website, including keyboard use, contrast, semantic structure, responsive layouts and feedback.' -Canonical "$SiteUrl/accessibility.html" -Active '' -Main $accessibilityMain -BodyClass 'policy-page')
