$operatingThread = @('Source','Instruction','Calculation or Work','Review','Action','Evidence','Status')
$validationThread = @('Test','Validate','Classify Errors','Identify Patterns','Recommend Logic Changes','Retest','Measure Improvement')

$homeSchema = @"
    <script type="application/ld+json">
      {"@context":"https://schema.org","@type":"Organization","name":"Axentra Solutions Pvt. Ltd.","url":"$SiteUrl/","logo":"$SiteUrl/assets/images/axentra-solutions-logo.jpeg","email":"$GeneralEmail","telephone":"+91 97250 24355","description":"Legal, commercial, mortgage, bankruptcy and product operations built around controlled operational follow-through.","sameAs":["$LinkedInUrl"]}
    </script>
"@

$homeMain = @"
<section class="home-hero">
  <img class="home-hero-image" src="$BasePath/assets/axentra-operations-visual.jpg" alt="Connected documents, review points and status markers representing a controlled operational workflow" width="1774" height="887" fetchpriority="high" />
  <div class="home-hero-overlay" aria-hidden="true"></div>
  <div class="container home-hero-content">
    <p class="eyebrow">Legal, commercial and product operations</p>
    <h1>Legal work is not complete when the document is complete</h1>
    <p>A contract, filing, claim, loan record, product output or legal instruction begins a chain of operational work. Axentra connects the source, instruction, calculation, owner, deadline, exception and evidence so the work remains visible from intake to closure.</p>
    <div class="button-row"><a class="button primary" href="$BasePath/how-we-work.html">Explore Our Operating Model</a><a class="button secondary" href="$BasePath/contact.html">Discuss a Workflow</a></div>
  </div>
</section>
<section class="section home-services"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Primary service lines</p><h2>Workflows where the document starts the operating requirement</h2></div><p>Axentra connects legal and commercial source material to calculation, review, action and reporting within the client's authorised process.</p></div>$serviceCards<div class="service-connection"><p><strong>Bankruptcy and mortgage workflows intersect</strong> where a borrower filing affects servicing, claims, payments, foreclosure activity and loan-system records. Each service retains its own process, controls and reporting structure.</p><a href="$BasePath/services/">View all service lines</a></div></div></section>
<section class="section section-dark operating-thread"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Axentra operating thread</p><h2>Preserve the basis for every action</h2></div><p>Every engagement identifies what starts the work, what information supports it, who owns each action, what requires review, what interrupts progress and what confirms completion.</p></div>$(Get-ProcessMarkup -Items $operatingThread -Label 'Axentra operating thread')</div></section>
<section class="section validation-loop"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Product and AI operations</p><h2>Validation corrects today. Error patterns inform tomorrow.</h2></div><p>Axentra classifies recurring corrections and converts them into recommendations for product logic, prompts, extraction instructions, playbooks, test cases and review rules.</p></div>$(Get-ProcessMarkup -Items $validationThread -Label 'Validation to improvement loop')<p class="process-caption">Validation corrects the current output. Structured error analysis helps improve the next batch.</p><a class="text-link" href="$BasePath/services/product-ai-operations.html">Explore Product and AI Operations</a></div></section>
<section class="section section-muted controls-preview"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Controls that follow the work</p><h2>Obligations move into delivery</h2></div><p>Relevant client obligations are translated into the people, vendor, access, device and process controls used for delivery.</p></div><div class="control-card-grid"><article><h3>People and providers</h3><p>Employment obligations, vendor flow-down, policies, workforce training and continuing confidentiality.</p></article><article><h3>Information</h3><p>Confidentiality, data protection, intellectual property, approved systems, retention, return and deletion.</p></article><article><h3>Assets and access</h3><p>IT asset guardrails, role-based access requirements, offboarding and access removal.</p></article><article><h3>Responsible delivery</h3><p>Responsible AI use, incident escalation and business-continuity requirements.</p></article></div><a class="text-link" href="$BasePath/security-trust.html">Review Security &amp; Trust</a></div></section>
<section class="section assessment-cta"><div class="container narrow"><p class="eyebrow">Workflow Assessment</p><h2>A requirement does not need to fit a pre-labelled service page</h2><p>Axentra evaluates the workflow, information, systems, required skills, data sensitivity, review model, exceptions and evidence of completion before establishing the delivery structure.</p><a class="button primary" href="$BasePath/contact.html?service=assessment">Discuss a Workflow</a></div></section>
"@

Write-SiteFile -Path 'index.html' -Content (Get-Page -Title 'Axentra | Legal, Commercial and Product Operations' -Description 'Axentra connects legal requirements to operational follow-through across bankruptcy, mortgage, contract, commercial, product and defined legal workflows.' -Canonical "$SiteUrl/" -Active 'home' -Main $homeMain -BodyClass 'home-page' -AdditionalHead $homeSchema)

# How We Work
$managedProcess = @('Understand','Configure','Transition','Deliver','Review and Improve')
$understand = @('Workflow','Volumes','Systems','Data','Dependencies','Deadlines','Outputs','Friction','Exceptions')
$configure = @('Team','Roles','Instructions','Access','IT assets','Security','Quality checks','Escalations','Reporting')
$transition = @('Knowledge transfer','Training','Policy acknowledgement','Access validation','Sample work','Calibration','Initial quality thresholds')
$deliver = @('Production','Review','Exceptions','Status','Evidence','Reporting','Dependencies')
$improve = @('Quality findings','Trend analysis','Root cause','Instruction updates','Training changes','Workflow changes','Technology feedback')
$bankruptcyPreTrack = @('Intake','Documents','Information Validation','Calculations','Forms','Filing Readiness')
$bankruptcyPostTrack = @('Filed Case','Docket and Deadlines','Trustee and Creditor Requirements','Claims and Hearings','Amendments and Payments','Discharge or Closure')
$bankruptcyCreditorTrack = @('Bankruptcy Notice','Loan and Case Match','Claim and Arrears Reconciliation','Proof of Claim','Plan and Payment Monitoring','Final Cure, Dismissal, Discharge or Closure')
$mortgageTrack = @('Loan Records','Servicing Activity','Calculations and Reconciliation','Delinquency','Loss Mitigation','Foreclosure or Bankruptcy','Account Closure')
$productTrack = @('Requirements','Test Design','Execution','Validation','Defect Analysis','Logic Recommendations','Retest','Release Evidence')

$howMain = @"
<section class="page-hero editorial-hero"><div class="container narrow"><p class="eyebrow">How we work</p><h1>Understand the workflow before configuring delivery</h1><p class="lead">Axentra begins with the event, information, systems, decisions, exceptions and evidence that define the work.</p><p>Design-thinking methods are used where they help uncover user needs, dependencies and friction. Client feedback remains part of delivery after transition, so instructions and operating evidence continue to shape the workflow.</p><a class="button primary" href="$BasePath/services/workflow-assessment.html">Explore Workflow Assessment</a></div></section>
<section class="section process-section"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Managed workflow delivery</p><h2>Configure, transition and improve against evidence</h2></div><p>The operating model establishes ownership, access, review, escalation and reporting before workload expands.</p></div>$(Get-ProcessMarkup -Items $managedProcess -Label 'Managed workflow delivery stages')</div></section>
<section class="section section-muted"><div class="container"><div class="scope-grid">$(Get-ScopePanel -Title 'Understand' -Items $understand -Open)$(Get-ScopePanel -Title 'Configure' -Items $configure -Open)$(Get-ScopePanel -Title 'Transition' -Items $transition)$(Get-ScopePanel -Title 'Deliver' -Items $deliver)$(Get-ScopePanel -Title 'Review and Improve' -Items $improve)</div></div></section>
<section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Bankruptcy delivery tracks</p><h2>Different case stages retain their own controls</h2></div><div class="track-stack"><article><h3>Pre-filing</h3>$(Get-ProcessMarkup -Items $bankruptcyPreTrack -Label 'Bankruptcy pre-filing track')</article><article><h3>Post-filing</h3>$(Get-ProcessMarkup -Items $bankruptcyPostTrack -Label 'Bankruptcy post-filing track')</article><article><h3>Creditor and mortgage-bankruptcy</h3>$(Get-ProcessMarkup -Items $bankruptcyCreditorTrack -Label 'Creditor and mortgage bankruptcy track')</article></div></div></section>
<section class="section section-dark"><div class="container"><div class="section-heading"><p class="eyebrow">Mortgage delivery track</p><h2>Keep servicing activity aligned with legal events</h2></div>$(Get-ProcessMarkup -Items $mortgageTrack -Label 'Mortgage delivery track')</div></section>
<section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Product assurance cycle</p><h2>Test through release evidence</h2></div>$(Get-ProcessMarkup -Items $productTrack -Label 'Product assurance cycle')</div></section>
$(Get-ContactBand -Heading 'Map the operating requirement before transition' -Copy 'The first discussion identifies the trigger, source information, systems, authorised decisions, delivery activities, exceptions and completion evidence.')
"@

Write-SiteFile -Path 'how-we-work.html' -Content (Get-Page -Title 'How We Work | Axentra' -Description 'Axentra assesses, configures, transitions, delivers and improves legal and business workflows while client instructions and feedback remain active throughout delivery.' -Canonical "$SiteUrl/how-we-work.html" -Active 'work' -Main $howMain -BodyClass 'how-page')

# Security and Trust
$peopleControls = @('Employment confidentiality obligations','Data-protection obligations','Intellectual-property obligations','Information-security obligations','Acceptable-use obligations','AI-use obligations','Continuing confidentiality obligations','Training and policy acknowledgement','Client-specific instructions')
$vendorControls = @('Confidentiality','Data protection','Intellectual property','Information security','AI use','Incident reporting','Access restrictions','Return and deletion','Subcontracting restrictions')
$policyAreas = @('Information security','Confidentiality and data handling','Privacy','Acceptable IT use','Remote working','Password and access management','AI use','Incident reporting','Retention and deletion','Vendor access')
$informationCategories = @('Confidential information','Personal data','Sensitive personal data','Protected health information','Intellectual property','Commercially sensitive information','Privileged material','Restricted records')
$responsibleAi = @('Client instructions','Contractual restrictions','Approved tools','Internal policies','Access controls','Data minimisation','Human review','Vendor flow-down','Escalation procedures')
$incidentControls = @('Internal reporting and escalation','Containment','Access suspension','Evidence preservation','Client-notification requirements','Corrective action','Recovery','Business continuity')

$securityMain = @"
<section class="page-hero editorial-hero"><div class="container narrow"><p class="eyebrow">Security &amp; Trust</p><h1>Controls must follow the information and the work</h1><p class="lead">Delivery requirements are translated into obligations for people, vendors, access, devices, systems, review and incident response.</p><p>Axentra describes and evidences the controls actually in place and does not represent itself as independently certified where certification has not been obtained.</p></div></section>
<section class="section section-muted"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">People and vendors</p><h2>Carry obligations through the delivery chain</h2></div><p>Engagement readiness addresses the obligations that apply to personnel and relevant providers before access to client information is approved.</p></div><div class="scope-grid">$(Get-ScopePanel -Title 'People-control areas' -Items $peopleControls -Open)$(Get-ScopePanel -Title 'Vendor flow-down areas' -Items $vendorControls -Open)</div></div></section>
<section class="section"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Policies and training</p><h2>Translate contractual requirements into operating instructions</h2><p>Policy acknowledgement, training and client-specific instructions form part of workflow configuration. Exact policy and training evidence is confirmed during diligence.</p></div><div>$(Get-ListMarkup -Items $policyAreas -ClassName 'output-list')</div></div></section>
<section class="section section-dark"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">IT assets and access</p><h2>Confirm the technical control set before processing</h2></div><p>The asset model, user responsibility, access approval, permitted software, remote-access method, logging, offboarding, return, deletion, recovery and continuity requirements are recorded for the agreed delivery environment.</p></div><div class="guardrail-grid"><article><h3>Before access</h3><p>Confirm the approved asset and access model, assigned role, permitted systems and client restrictions.</p></article><article><h3>During delivery</h3><p>Apply the agreed device, authentication, download, media, software and remote-working rules.</p></article><article><h3>When access changes</h3><p>Suspend or remove access, preserve required records, return assets and complete agreed deletion or reassignment steps.</p></article></div><p class="security-caveat">Specific endpoint, MFA, VPN, VDI, encryption, backup and technical architecture claims remain excluded from this public page until independently verified.</p></div></section>
<section class="section"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Information categories</p><h2>Match safeguards to the information involved</h2><p>The applicable control set is determined by the information involved, the client environment, contractual requirements and the agreed delivery model.</p></div><div>$(Get-ListMarkup -Items $informationCategories -ClassName 'output-list')</div></div></section>
<section class="section section-muted"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Responsible AI use</p><h2>Approved purpose, approved tool, accountable review</h2></div><p class="statement">Client information is not entered into unauthorised public AI tools or used for independent model training.</p></div>$(Get-ListMarkup -Items $responsibleAi -ClassName 'output-list')</div></section>
<section class="section"><div class="container"><div class="scope-grid">$(Get-ScopePanel -Title 'Incident and continuity controls' -Items $incidentControls -Intro 'The response path is configured against contractual and client-notification requirements.' -Open)<article class="static-panel"><p class="eyebrow">PHI and HIPAA</p><h2>Role and safeguards first</h2><p>Where an engagement involves protected health information, the role of each party, permitted use, safeguards, access environment, incident requirements and Business Associate Agreement obligations are addressed before processing begins.</p><p>Axentra does not describe itself as HIPAA certified.</p></article></div></div></section>
$(Get-ContactBand -Eyebrow 'Security diligence' -Heading 'Review information, access and delivery requirements before scope is finalised' -Copy 'Security commitments are documented against the client environment and the information involved. Confidential technical architecture is shared only through an appropriate diligence process.')
"@

Write-SiteFile -Path 'security-trust.html' -Content (Get-Page -Title 'Security and Trust | Axentra' -Description 'Axentra Security and Trust explains people, vendor, policy, access, responsible AI, incident, continuity and information-control requirements without unsupported certification claims.' -Canonical "$SiteUrl/security-trust.html" -Active 'security' -Main $securityMain -BodyClass 'security-page')

# About
$ethos = @(
  [pscustomobject]@{Title='Preserve the thread'; Copy='Work remains connected to its source, instruction, calculation, owner, deadline, review point and evidence.'},
  [pscustomobject]@{Title='Make exceptions visible'; Copy='Missing information, deviations, dependencies and unresolved questions are recorded and routed rather than left in inboxes or informal conversations.'},
  [pscustomobject]@{Title='Establish control before scale'; Copy='Instructions, access, security, calculations, quality and escalation arrangements are validated before workload is expanded.'},
  [pscustomobject]@{Title='Let technology follow the workflow'; Copy="Tools, automation and AI operate within the client's approved environment and business requirements."},
  [pscustomobject]@{Title='Carry obligations through delivery'; Copy='Confidentiality, privacy, intellectual property, information security and AI-use requirements are reflected across contracts, policies, training, vendors, access and IT assets.'},
  [pscustomobject]@{Title='Learn from the evidence'; Copy='Quality findings, exceptions, turnaround information and client feedback strengthen the workflow over time.'}
)
$ethosMarkup = ($ethos | ForEach-Object { '<article><h3>{0}</h3><p>{1}</p></article>' -f $_.Title, $_.Copy }) -join "`n"

$aboutMain = @"
<section class="page-hero editorial-hero"><div class="container narrow"><p class="eyebrow">About Axentra</p><h1>Build a controlled operating layer around legal and business work</h1><p class="lead">Legal and business work often loses clarity as it moves away from the original document, decision or product output. Instructions become tasks, tasks move across teams, exceptions are handled informally and evidence becomes distributed across systems.</p><p>Axentra was established to build a more controlled operational layer around that movement.</p></div></section>
<section class="section section-muted"><div class="container purpose-grid"><article><p class="eyebrow">Vision</p><h2>Keep the work connected</h2><p>For legal requirements, financial information, business actions and supporting evidence to remain connected from the beginning of a workflow to its completion.</p></article><article><p class="eyebrow">Mission</p><h2>Operate for reviewability</h2><p>To design and operate secure, reviewable legal and business workflows that preserve context across documents, calculations, people, systems, decisions, deadlines and handoffs.</p></article></div></section>
<section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Operating ethos</p><h2>Principles carried into delivery</h2></div><div class="ethos-grid">$ethosMarkup</div></div></section>
<section class="section section-dark" id="leadership"><div class="container"><div class="section-heading"><p class="eyebrow">Leadership</p><h2>Company direction and service design</h2></div><div class="leader-grid"><article><p class="role">Founder</p><h3>Gagan Prajapati</h3><p>Gagan Prajapati is the Founder of Axentra Solutions. He works on company direction, partnerships and governance, while client delivery is managed through Axentra's service and operations teams.</p><a class="text-link light-link" href="https://www.linkedin.com/in/gagan-prajapati-6b3439a5/" target="_blank" rel="noopener noreferrer">Gagan on LinkedIn</a></article><article><p class="role">Co-founder</p><h3>Pooja Gore</h3><p>Pooja Gore is Co-founder of Axentra Solutions. She contributes to business development, client engagement and service models shaped around each client's workflows, systems and operating requirements.</p><a class="text-link light-link" href="https://www.linkedin.com/in/pooja-gore-99712723b/" target="_blank" rel="noopener noreferrer">Pooja on LinkedIn</a></article></div></div></section>
$(Get-ContactBand -Heading 'Discuss the operating requirement with Axentra' -Copy 'Begin with the workflow, current systems, review responsibility, constraints and evidence expected at completion.')
"@

Write-SiteFile -Path 'about.html' -Content (Get-Page -Title 'About Axentra' -Description 'Axentra builds controlled legal and business operations that preserve context across documents, calculations, people, systems, decisions, deadlines and handoffs.' -Canonical "$SiteUrl/about.html" -Active 'about' -Main $aboutMain -BodyClass 'about-page')

# Insights
$insightCategories = @('Bankruptcy operations','Mortgage servicing and default operations','Contract and commercial operations','Product and AI assurance','Legal operations','Quality and workflow controls','Information security','Commercial contract data')
$categoryMarkup = ($insightCategories | ForEach-Object { "<li>$_</li>" }) -join "`n"
$insightsMain = @"
<section class="page-hero editorial-hero"><div class="container narrow"><p class="eyebrow">Insights</p><h1>Operational questions behind legal and commercial work</h1><p class="lead">Published observations on workflow design, contract operations, quality and the evidence that carries work from instruction to completion.</p><a class="button secondary" href="$LinkedInUrl" target="_blank" rel="noopener noreferrer">Follow Axentra on LinkedIn</a></div></section>
<section class="section section-muted"><div class="container"><div class="section-heading"><p class="eyebrow">Topics</p><h2>Insight categories</h2></div><ul class="category-list" aria-label="Insight categories">$categoryMarkup</ul></div></section>
<section class="section"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Published posts</p><h2>Read from the source</h2></div><p>Only articles and LinkedIn posts already published by Axentra are linked here.</p></div><div class="insight-grid"><article class="insight-card"><div class="insight-tags"><span>Legal operations</span><span>Quality and workflow controls</span></div><h3>Operational design for scalable business operations</h3><p>How workflow, ownership and operating controls support structured delivery.</p><a href="https://www.linkedin.com/posts/axentra-solutions-pvt-ltd_axentrasolutions-alsp-legaloperations-activity-7459630423296479233-0-J5" target="_blank" rel="noopener noreferrer">Read on LinkedIn</a></article><article class="insight-card"><div class="insight-tags"><span>Contract operations</span><span>Commercial contract data</span></div><h3>Vendor contract review: from clauses to operations</h3><p>Why contract review must connect approved language to downstream commercial activity.</p><a href="https://www.linkedin.com/posts/axentra-solutions-pvt-ltd_vendor-contract-review-from-clauses-to-operations-activity-7475593440907653120-kHWk" target="_blank" rel="noopener noreferrer">Read on LinkedIn</a></article></div></div></section>
<section class="section insight-faq-link"><div class="container compact-split"><div><p class="eyebrow">Looking for a direct answer?</p><h2>Service and operating questions are kept in a separate FAQ library</h2></div><a class="button secondary" href="$BasePath/faqs.html">Browse FAQs</a></div></section>
"@

Write-SiteFile -Path 'insights/index.html' -Content (Get-Page -Title 'Insights | Axentra' -Description 'Axentra insights on bankruptcy, mortgage, contract and commercial operations, product assurance, legal operations, quality controls and information security.' -Canonical "$SiteUrl/insights/" -Active 'insights' -Main $insightsMain -BodyClass 'insights-page')

# Contact
$contactMain = @"
<section class="page-hero editorial-hero"><div class="container narrow"><p class="eyebrow">Contact Axentra</p><h1>Discuss the workflow and the operating requirement</h1><p class="lead">Share the work trigger, source information, current systems, review responsibility, approximate workload and the point where follow-through becomes difficult to see.</p><div class="contact-direct"><a href="mailto:$GeneralEmail">$GeneralEmail</a><a href="tel:+919725024355">+91 97250 24355</a><a href="$LinkedInUrl" target="_blank" rel="noopener noreferrer">Axentra on LinkedIn</a></div></div></section>
<section class="section"><div class="container contact-layout"><div class="contact-form-intro"><p class="eyebrow">Workflow enquiry</p><h2>Start with enough context to assess the requirement</h2><p>The form prepares an email in your email application. The website does not transmit or store the entries.</p><p class="form-warning">Do not submit confidential information, personal data, protected health information, borrower records, case documents, loan documents or client files through this form. Secure information-transfer arrangements are established separately.</p></div><form class="contact-form" id="contact-form" novalidate><div class="form-row"><label for="contact-name">Name</label><input id="contact-name" name="name" autocomplete="name" required /></div><div class="form-row"><label for="contact-organisation">Organisation</label><input id="contact-organisation" name="organisation" autocomplete="organization" required /></div><div class="form-row"><label for="contact-email">Work email</label><input id="contact-email" name="email" type="email" autocomplete="email" required /></div><div class="form-row"><label for="contact-service">Service interest</label><select id="contact-service" name="service" required><option value="">Select a service</option><option>Bankruptcy Operations</option><option>Mortgage Servicing and Default Operations</option><option>Contract and Commercial Operations</option><option>Product and AI Operations</option><option>Defined Legal Support</option><option>Workflow Assessment</option><option>Other</option></select></div><div class="form-row full"><label for="contact-requirement">Brief workflow or requirement</label><textarea id="contact-requirement" name="requirement" rows="5" required></textarea></div><div class="form-row"><label for="contact-volume">Approximate volume or workload</label><input id="contact-volume" name="volume" /></div><div class="form-row"><label for="contact-method">Preferred contact method</label><input id="contact-method" name="preferred_contact" placeholder="Email, phone or LinkedIn" required /></div><div class="form-actions full"><button class="button primary" type="submit">Prepare Email</button><p class="form-status" id="form-status" role="status" aria-live="polite"></p></div></form></div></section>
"@

Write-SiteFile -Path 'contact.html' -Content (Get-Page -Title 'Contact Axentra' -Description 'Contact Axentra to discuss a bankruptcy, mortgage, contract, product, legal-support or workflow-assessment requirement.' -Canonical "$SiteUrl/contact.html" -Active 'contact' -Main $contactMain -BodyClass 'contact-page')

# Legal Notice
$legalMain = @"
<section class="page-hero policy-hero"><div class="container narrow"><p class="eyebrow">Legal Notice</p><h1>Website and service boundaries</h1><p>Clear terms for use of this website and the role Axentra describes on it.</p></div></section>
<section class="section"><div class="container policy-content"><h2>Axentra's role</h2><p>Axentra Solutions Pvt. Ltd. is not a law firm and does not provide legal representation. Use of this website, submission of an enquiry or communication with Axentra does not create a lawyer-client relationship.</p><p>Website information is general and is not legal, financial, lending, servicing, tax or other professional advice.</p><h2>Mortgage and bankruptcy boundaries</h2><p>Axentra does not act as a lender, licensed mortgage servicer, foreclosure counsel or debt collector unless a role is separately authorised and all applicable requirements are confirmed. Operational support remains within client-approved systems, instructions, decisions and review.</p><h2>Website use</h2><p>Use the website lawfully and do not attempt to interfere with its availability, security or content. Do not send client files or sensitive records through general website or email channels unless a secure transfer arrangement has been established.</p><h2>Intellectual property</h2><p>Website content, branding and original materials belong to Axentra or the relevant owner. They must not be represented as another party's work or reused in a misleading manner.</p><h2>External links</h2><p>External links are provided for reference. A link does not imply endorsement, control or responsibility for the external service or its content.</p><h2>Contact</h2><p>Questions about this notice may be sent to <a href="mailto:$GeneralEmail">$GeneralEmail</a>.</p></div></section>
"@

Write-SiteFile -Path 'legal-notice.html' -Content (Get-Page -Title 'Legal Notice | Axentra' -Description 'Axentra legal notice covering website use, service boundaries, no lawyer-client relationship, intellectual property, external links and contact information.' -Canonical "$SiteUrl/legal-notice.html" -Active '' -Main $legalMain -BodyClass 'policy-page')

# Privacy Notice
$privacyMain = @"
<section class="page-hero policy-hero"><div class="container narrow"><p class="eyebrow">Privacy Notice</p><h1>Website enquiries and information handling</h1><p>This notice describes information handled through the public Axentra website and general contact routes.</p></div></section>
<section class="section"><div class="container policy-content"><h2>Information provided by you</h2><p>The contact form prepares an email in your own email application. The website does not transmit or store the fields. If you send the email, Axentra receives the name, organisation, work email, service interest, workflow description, workload and contact preference you choose to include.</p><p>Axentra also receives information sent directly to its published email addresses or LinkedIn account.</p><h2>Purpose</h2><p>Enquiry information is used to respond, understand the stated requirement, arrange a discussion, maintain relevant correspondence and meet legal or security obligations.</p><h2>Technical information and analytics</h2><p>The website code does not use analytics, advertising trackers, account profiles or tracking cookies. It does not set optional cookies. GitHub Pages hosts the website and may process standard technical request information under its own terms.</p><h2>Storage, access and service providers</h2><p>Information sent by email is stored in the applicable email environment and accessed by personnel involved in responding to the enquiry, subject to organisational and provider controls. Hosting and communication providers process information only for the services they provide.</p><h2>Retention</h2><p>Enquiry records are retained only for a relevant business, security, contractual or legal purpose, then deleted or retained under the applicable record requirement.</p><h2>Your choices and rights</h2><p>You may ask Axentra to access, correct or delete enquiry information, or raise a privacy question. Applicable rights depend on the information and governing law.</p><h2>Contact</h2><p>Send privacy requests to <a href="mailto:$GeneralEmail">$GeneralEmail</a>. Do not include sensitive case, borrower, health, loan or client records in the first message.</p></div></section>
"@

Write-SiteFile -Path 'privacy-notice.html' -Content (Get-Page -Title 'Privacy Notice | Axentra' -Description 'Axentra website privacy notice covering contact-form and email enquiries, technical information, analytics, storage, access, retention, providers and user rights.' -Canonical "$SiteUrl/privacy-notice.html" -Active '' -Main $privacyMain -BodyClass 'policy-page')

# Accessibility
$accessibilityMain = @"
<section class="page-hero policy-hero"><div class="container narrow"><p class="eyebrow">Accessibility</p><h1>Access to Axentra's website</h1><p>The website is designed for keyboard use, readable contrast, responsive layouts and clear content structure.</p></div></section>
<section class="section"><div class="container policy-content"><h2>Accessibility measures</h2><p>Pages use semantic headings and landmarks, visible keyboard focus, a skip link, text alternatives for meaningful images, labelled form controls and process lists that remain readable without visual connectors.</p><h2>Responsive use</h2><p>Navigation, service scopes, process steps and contact fields adapt for desktop, tablet and mobile screens. Motion is limited and disabled where a user requests reduced motion.</p><h2>Feedback</h2><p>If any page, control or document is difficult to use, email <a href="mailto:$GeneralEmail">$GeneralEmail</a> with the page address and a short description of the problem.</p></div></section>
"@

Write-SiteFile -Path 'accessibility.html' -Content (Get-Page -Title 'Accessibility | Axentra' -Description 'Accessibility information for the Axentra website, including keyboard use, contrast, semantic structure, responsive layouts and feedback.' -Canonical "$SiteUrl/accessibility.html" -Active '' -Main $accessibilityMain -BodyClass 'policy-page')
