$serviceCards = @"
<div class="service-grid primary-services">
  <article class="service-card service-bankruptcy"><p class="service-number">01</p><h2>Bankruptcy Operations</h2><p>Pre-filing preparation, financial calculations, filing-readiness support and post-filing case administration across debtor, creditor, lender and servicer workflows.</p><a href="$BasePath/services/bankruptcy-operations.html">Explore Bankruptcy Operations</a></article>
  <article class="service-card service-mortgage"><p class="service-number">02</p><h2>Mortgage Servicing and Default Operations</h2><p>Loan-document administration, account reconciliation, delinquency, loss-mitigation, foreclosure and bankruptcy-interface support. Performing-loan and post-foreclosure scope requires separate confirmation.</p><a href="$BasePath/services/mortgage-servicing-default-operations.html">Explore Mortgage Operations</a></article>
  <article class="service-card service-contract"><p class="service-number">03</p><h2>Contract and Commercial Operations</h2><p>Contract intake, approved-template drafting, review coordination, execution, repository administration, obligations, commercial data and operational follow-through.</p><a href="$BasePath/services/contract-commercial-operations.html">Explore Contract Operations</a></article>
  <article class="service-card service-product"><p class="service-number">04</p><h2>Product and AI Operations</h2><p>Domain UAT, extraction and summary validation, defect analysis, recurring-error trends, logic recommendations and regression testing.</p><a href="$BasePath/services/product-ai-operations.html">Explore Product Operations</a></article>
</div>
<div class="service-grid supporting-services">
  <article class="service-card compact"><p class="service-number">05</p><h2>Defined Legal Support</h2><p>Research, approved-template drafting support, document review, chronologies, due diligence and structured legal reporting.</p><a href="$BasePath/services/defined-legal-support.html">Explore Defined Legal Support</a></article>
  <article class="service-card compact"><p class="service-number">06</p><h2>Workflow Assessment</h2><p>A structured review of workflow, information, systems, skills, controls, exceptions, review responsibility and evidence of completion.</p><a href="$BasePath/services/workflow-assessment.html">Explore Workflow Assessment</a></article>
</div>
"@

$servicesMain = @"
<section class="page-hero editorial-hero">
  <div class="container narrow">
    <p class="eyebrow">Axentra services</p>
    <h1>Operations connected to their legal and commercial source</h1>
    <p class="lead">Six service lines address document-heavy, calculation-sensitive and deadline-driven work without losing the instruction, review point or evidence behind it.</p>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="section-heading split-heading"><div><p class="eyebrow">Primary service lines</p><h2>Defined scope. Connected follow-through.</h2></div><p>Each engagement is configured around client systems, approved methods, role boundaries and reporting requirements.</p></div>
    $serviceCards
  </div>
</section>
<section class="section section-dark">
  <div class="container connected-services">
    <div><p class="eyebrow">Connected, not combined</p><h2>Bankruptcy and mortgage operations meet at specific events</h2></div>
    <p>Bankruptcy and mortgage workflows intersect where a borrower filing affects servicing, claims, payments, foreclosure activity and loan-system records. Each service retains its own process, controls and reporting structure.</p>
  </div>
</section>
$(Get-ContactBand -Heading 'Assess the work before defining the delivery model' -Copy 'Axentra maps the trigger, inputs, systems, decisions, exceptions, controls and completion evidence before transition.')
"@

Write-SiteFile -Path 'services/index.html' -Content (Get-Page -Title 'Services | Axentra' -Description 'Explore Axentra services across bankruptcy, mortgage servicing and default, contract and commercial operations, product and AI operations, defined legal support and workflow assessment.' -Canonical "$SiteUrl/services/" -Active 'services' -Main $servicesMain -BodyClass 'services-page')

# Bankruptcy Operations
$bankruptcyProcess = @('Intake and Source Documents','Information Validation','Calculations and Financial Schedules','Petition and Filing Preparation','Filing-Readiness Review','Post-Filing Administration','Claims, Deadlines and Hearings','Case Completion and Reporting')
$bankruptcyPrefiling = @(
  'Prospective-client and matter-intake administration','Conflict-check information collation within client processes','Client questionnaire administration','Document-request checklists','Identity and household information','Employment and income documents','Pay-stub review','Bank-statement collation','Tax returns and tax transcripts','Asset information','Secured and unsecured debt information','Creditor statements','Loan and account number validation','Lawsuits, judgments and garnishments','Domestic-support obligations','Leases and executory contracts','Business interests','Property transfers','Recent financial transactions','Insurance records','Retirement account records','Credit-counselling certificate tracking','Filing-fee or instalment information','Missing-document tracking','Inconsistency identification','Exception identification','Follow-up request preparation','Document indexing and file naming','Matter chronology','Data entry into approved bankruptcy software','Source-to-form traceability','Sensitive-information and redaction checks','Signature-package preparation','Attorney-review package preparation'
)
$bankruptcyIncome = @('Gross income collation','Payroll-frequency normalisation','Six-month income history','Current monthly income support','Annualised income','Household income aggregation','Spousal income','Non-employment income','Rental income','Business income and expenses','Household contributions','Client-approved income exclusions','Income-source reconciliation','Median-income comparison support')
$bankruptcyChapter7 = @('Form B122A-1 data preparation','State and household-size information','Median-income inputs','Form B122A-2 worksheet support','National-standard expense inputs','Local-standard expense inputs','Secured-debt payments','Priority-debt information','Additional-expense documentation','Disposable-income worksheet support','Source-reference and formula checks','Exception and attorney-review flags')
$bankruptcyChapter13 = @('Form B122C-1 data preparation','Commitment-period support','Form B122C-2 disposable-income support','Current monthly income reconciliation','Schedule I income and Schedule J expenses','Net monthly income','Secured-debt arrears','Priority claims','Ongoing secured payments','Executory-contract and lease payments','Trustee-fee inputs provided by the client','Attorney-fee treatment provided by the client','Plan-payment and duration worksheets','Disposable-income comparison','Feasibility-data preparation','Payment-change scenarios','Amended-plan calculations')
$bankruptcyAssets = @('Asset values','Secured balances and lien information','Estimated equity','Co-owner information','Exemption data entered under attorney instruction','Secured and unsecured debt totals','Priority and non-priority debt categorisation','Contingent, disputed and unliquidated claim flags','Asset and liability reconciliation','Schedule consistency checks','Source-document consistency checks')
$bankruptcyFees = @('Filing-fee information','Instalment-request information','Fee-waiver information support','Attorney-fee information supplied by the client','Pre-filing payment records','Trustee or administrative payment inputs','Cost and payment schedule summaries')
$bankruptcyCalculationControls = @('Source-to-calculation traceability','Formula validation','Duplicate-entry and missing-entry checks','Pay-frequency and date-period checks','Household-size consistency','Form-to-schedule reconciliation','Income-to-bank-record comparison','Secured-balance reconciliation','Version control','Official-data confirmation','Reviewer sign-off','Exception log','Attorney escalation')
$bankruptcyFiling = @('Voluntary-petition data','Schedule A/B property information','Schedule C data entered under attorney instruction','Schedule D secured claims','Schedule E/F unsecured claims','Schedule G executory contracts and leases','Schedule H co-debtors','Schedule I income and Schedule J expenses','Statement of Financial Affairs','Statement of Intention','Creditor matrix and address validation','Means-test form assembly','Local-form support','Filing-fee documentation','Credit-counselling certificate','Declaration and signature tracking','Sensitive-data, SSN and redaction checks','Cross-form reconciliation','Missing-field checks','Supporting-document checklist','Filing-package organisation','Filing-readiness report','Attorney-review and approval trackers')
$bankruptcyCaseSetup = @('Filed-document collection','Case number, court, judge and trustee details','Filing-date verification','Automatic-stay and notice-of-bankruptcy event records','Case calendar and deadline extraction','Client system updates','Filed-versus-prepared comparison','Initial docket review','Deficiency tracking')
$bankruptcyTrustee = @('Section 341 meeting date','Trustee document requests','Document production package','Missing-document follow-up','Meeting-preparation checklist','Updated income, bank and tax records','Trustee correspondence','Continued or rescheduled meeting tracking','Post-meeting action tracker')
$bankruptcyDocket = @('PACER and court-docket monitoring under an approved access model','Docket-event classification','Hearing, objection, motion and response deadlines','Confirmation dates','Claims and government claims bar dates','Reaffirmation deadlines','Financial-management course tracking','Discharge-related deadlines','Case-status summaries','Material-event escalation')
$bankruptcyAmendments = @('Deficiency-notice review','Missing-form tracker','Amended schedule preparation support','Updated creditor, income and expense information','Amendment comparison','Signature tracking','Filing-package organisation','Amendment-status reporting')
$bankruptcyClaims = @('Claims-register monitoring','Proof-of-claim collection','Claim abstraction','Creditor and account matching','Claim amount and classification','Secured, priority and unsecured claim tracking','Duplicate-claim flags','Amended and transferred claims','Supporting-document checks','Claim-versus-schedule comparison','Objection-review support','Bar-date reporting','Claim reconciliation')
$bankruptcyChapter7Post = @('Trustee-request tracking','Asset-case and no-asset events','Statement-of-intention administration','Reaffirmation-document administration','Redemption-document support','Motion and hearing trackers','Distribution records','Discharge and closing-event tracking','Final file organisation')
$bankruptcyChapter13Post = @('Plan filing, amendments and confirmation hearing records','Objections and responses','Claims reconciliation','Plan-payment information','Trustee notices','Pre-petition and post-petition payment records','Mortgage cure information and ongoing mortgage payments','Payment changes and plan-modification calculations','Post-confirmation amendments','Delinquency and default events','Motion-to-dismiss and motion-for-relief trackers','Completion documents','Financial-management course','Final cure and final payment records','Discharge and case-closing administration')
$bankruptcyCreditor = @('Bankruptcy-notice intake','Borrower, loan and case matching','Chapter, filing date and automatic-stay status','Loan-system and legal-event updates','Counsel referral package','Proof-of-claim and Official Form 410 data support','Mortgage Proof of Claim Attachment support','Principal, interest, arrears and escrow reconciliation','Fees, expenses and charges','Payment-history review','Supporting-document package','Claims bar-date tracking','Amended proof or transfer of claim records','Payment-change and post-petition fee notice support','Plan and confirmation-order abstraction','Pre-petition and post-petition payment monitoring','Critical dates','Motion-for-relief referral support','Objection and response trackers','Final cure and final payment records','Dismissal, conversion, discharge and case closure','Loan-system reconciliation','Counsel and servicer reporting')
$bankruptcyOutputs = @('Intake tracker','Document-readiness tracker','Missing-information register','Exception register','Source-indexed matter file','Income and expense worksheets','Means-test support workbook','Schedule I and J reconciliation','Chapter 13 calculation workbook','Creditor matrix','Filing-readiness checklist','Petition support package','Deadline and hearing calendars','Trustee-request tracker','Claims register','Docket-event report','Amendment tracker','Mortgage arrears worksheet','Payment and cure tracker','Case-status dashboard','Quality findings report','Closing checklist')

$bankruptcyMain = @"
<section class="page-hero service-detail-hero">
  <div class="container narrow"><p class="eyebrow">Primary service line</p><h1>Bankruptcy Operations</h1><p class="lead">Connected support across pre-filing preparation, financial calculations, filing readiness and post-filing case administration.</p><p>Bankruptcy work does not begin with filing the petition or end when documents are submitted to the court. Information moves from client intake into financial schedules, creditor records, calculations, forms, filing requirements, trustee requests, claims, hearings, amendments, payments and case-closing activities.</p><p>Axentra keeps the source information, calculation, form, deadline, required action, review point and case status connected throughout the workflow. Delivery follows the law firm's, lender's, servicer's or authorised client team's systems, instructions, templates and review structure.</p><a class="button primary" href="$BasePath/contact.html?service=bankruptcy">Discuss Bankruptcy Operations</a></div>
</section>
<section class="section process-section"><div class="container"><div class="section-heading"><p class="eyebrow">Bankruptcy workflow</p><h2>From source documents to case reporting</h2></div>$(Get-ProcessMarkup -Items $bankruptcyProcess -Label 'Bankruptcy operations workflow' -ClassName 'process-eight')</div></section>
<section class="section section-muted"><div class="container detail-layout"><div class="section-intro"><p class="section-index">01</p><p class="eyebrow">Pre-filing preparation</p><h2>Build a reviewable source record before forms are finalised</h2><p>Missing, conflicting or unclear information is recorded and routed under the client's review and escalation process.</p></div><div>$(Get-ScopePanel -Title 'Pre-filing preparation scope' -Items $bankruptcyPrefiling -Intro 'The work connects intake material to the approved software, forms and attorney-review package.' -Open)</div></div></section>
<section class="section calculations-section"><div class="container"><div class="section-heading split-heading"><div><p class="section-index">02</p><p class="eyebrow">Calculations and financial schedules</p><h2>Source-linked calculation support</h2></div><div><p>Bankruptcy calculations depend on complete source information, current official data, the applicable chapter, local requirements and the legal treatment approved by the responsible attorney.</p><p>Axentra supports preparation, reconciliation and quality review of calculation worksheets using client-approved methodologies, official forms and current source data.</p></div></div><div class="scope-grid">$(Get-ScopePanel -Title 'Income calculations' -Items $bankruptcyIncome -Open)$(Get-ScopePanel -Title 'Chapter 7 calculation support' -Items $bankruptcyChapter7)$(Get-ScopePanel -Title 'Chapter 13 calculation support' -Items $bankruptcyChapter13 -Intro 'Plan calculations follow attorney-approved claim treatment, jurisdiction-specific requirements and client instructions.')$(Get-ScopePanel -Title 'Asset, liability and equity worksheets' -Items $bankruptcyAssets)$(Get-ScopePanel -Title 'Filing-fee and case-cost worksheets' -Items $bankruptcyFees)$(Get-ScopePanel -Title 'Calculation quality controls' -Items $bankruptcyCalculationControls)</div><p class="boundary-note">Axentra prepares and validates calculation support. Legal conclusions, chapter selection, exemptions, claim treatment and filing approval remain within the client's authorised review process.</p></div></section>
<section class="section section-muted"><div class="container detail-layout"><div class="section-intro"><p class="section-index">03</p><p class="eyebrow">Filing preparation and readiness</p><h2>Assemble the file for authorised review</h2><p>Electronic submission or filing support operates only within the client's authorised system, role allocation and approval process.</p></div><div>$(Get-ScopePanel -Title 'Filing preparation and readiness scope' -Items $bankruptcyFiling -Open)</div></div></section>
<section class="section"><div class="container"><div class="section-heading split-heading"><div><p class="section-index">04</p><p class="eyebrow">Post-filing case administration</p><h2>Keep docket events, actions and evidence connected</h2></div><p>After filing, the case continues through notices, trustee requirements, creditor activity, hearings, amendments, payments, plan events and closing requirements. Axentra maintains the connection between the court docket, client file, required action, responsible owner, deadline and supporting evidence.</p></div><div class="scope-grid">$(Get-ScopePanel -Title 'Case setup' -Items $bankruptcyCaseSetup -Open)$(Get-ScopePanel -Title 'Trustee and meeting support' -Items $bankruptcyTrustee)$(Get-ScopePanel -Title 'Docket and deadline administration' -Items $bankruptcyDocket)$(Get-ScopePanel -Title 'Amendment and deficiency support' -Items $bankruptcyAmendments)$(Get-ScopePanel -Title 'Claims administration' -Items $bankruptcyClaims)$(Get-ScopePanel -Title 'Chapter 7 post-filing support' -Items $bankruptcyChapter7Post)$(Get-ScopePanel -Title 'Chapter 13 post-filing support' -Items $bankruptcyChapter13Post)</div></div></section>
<section class="section section-dark"><div class="container detail-layout"><div class="section-intro"><p class="section-index">05</p><p class="eyebrow">Creditor and mortgage-bankruptcy operations</p><h2>Reconcile the case event with the loan and claim record</h2><p>This scope supports record preparation and administration. It does not include pleading signature, court appearance or litigation strategy.</p><a class="text-link light-link" href="$BasePath/services/mortgage-servicing-default-operations.html">See Mortgage Servicing and Default Operations</a></div><div>$(Get-ScopePanel -Title 'Creditor and mortgage-bankruptcy scope' -Items $bankruptcyCreditor -Open)</div></div></section>
<section class="section outputs-section"><div class="container"><div class="section-heading"><p class="eyebrow">Typical delivery outputs</p><h2>Records that show readiness, action and status</h2></div>$(Get-ListMarkup -Items $bankruptcyOutputs -ClassName 'output-list')</div></section>
$(Get-ContactBand -Eyebrow 'Bankruptcy operations' -Heading 'Review a pre-filing, calculation or case-administration workflow' -Copy 'Share the case stage, source records, approved systems, calculation method, review responsibility and reporting requirement.')
"@

Write-SiteFile -Path 'services/bankruptcy-operations.html' -Content (Get-Page -Title 'Bankruptcy Operations | Axentra' -Description 'Bankruptcy operations support across pre-filing preparation, Chapter 7 and Chapter 13 calculations, filing readiness, dockets, claims and post-filing case administration.' -Canonical "$SiteUrl/services/bankruptcy-operations.html" -Active 'services' -Main $bankruptcyMain -BodyClass 'service-detail-page bankruptcy-page')

# Mortgage Servicing and Default Operations
$mortgageProcess = @('Loan and Document Onboarding','Calculations and Reconciliation','Delinquency and Borrower Support','Loss-Mitigation Administration','Foreclosure and Legal Tracking','Bankruptcy Interface','Case or Account Closure')
$mortgageOnboarding = @('Loan boarding support','Borrower and property-data validation','Promissory note, mortgage and deed-of-trust information','Assignment, allonge and endorsement records','Title-policy information and legal description','Loan number and investor identification','Origination, modification and forbearance documents','Payment-history setup','Escrow, insurance and tax information','Missing-document and collateral exception trackers','Repository records','Source-to-system validation','Servicing-transfer review','Data and document reconciliation')
$mortgageCalculations = @('Unpaid principal balance','Principal and interest breakdown','Interest-accrual worksheet and per-diem interest','Escrow balance, shortage and surplus','Tax and insurance advances','Late fees, recoverable fees and expenses','Corporate advances','Suspense amounts and unapplied funds','Delinquency amount','Pre-petition and post-petition arrears','Reinstatement and payoff amount support','Payment-history reconciliation','Modification trial payments and modified payment','Capitalised amount and deferred balance','Forbearance and repayment-plan information','Shortfall and deficiency data','Claim and recovery worksheets','Investor reporting reconciliation')
$mortgageDelinquency = @('Delinquency status and missed-payment identification','Days-past-due tracking','Borrower-contact activity and communication records','Notice tracker and right-party-contact information','Promise-to-pay records','Delinquency-reason classification','Hardship information','Assistance-package administration','Required-document checklist','Incomplete-information tracker','Escalation and exception records','Property-inspection, occupancy and condition records','Insurance and tax exceptions','Investor-status reporting','Specialist and counsel referral packages')
$mortgageLossMitigation = @('Assistance-package intake and application date','Completeness review against approved checklists','Missing-document correspondence from approved templates','Income, expense, hardship, property, occupancy, tax and insurance information','Version control and document-expiry tracking','Evaluation inputs','Waterfall worksheet inputs under approved rules','Retention-option and non-retention-option records','Forbearance and repayment-plan administration','Modification-document support and trial-payment tracking','Short-sale and deed-in-lieu documents','Offer, response and appeal deadlines','Acceptance and denial correspondence administration','Foreclosure-hold and dual-track records','Quality review and supporting-document records')
$mortgageForeclosure = @('Foreclosure referral and counsel instruction packages','Document-readiness review','Note, mortgage and assignment records','Payment history','Default and acceleration notices','Reinstatement and payoff information','Referral date and milestone tracking','Title-search and title-report administration','Title-defect tracker','Property information','Service, publication, hearing and sale milestones','Complaint or petition support records','Bid and judgment information provided by the client','Fee and cost records','Loss-mitigation and bankruptcy holds','Client-required compliance-check tracking','Counsel invoice review and status tracking','Post-sale document administration')
$mortgageBankruptcy = @('Bankruptcy notice','Borrower, loan and case matching','Chapter, filing date and automatic-stay record','Counsel referral','Loan-system bankruptcy code','Proof-of-claim data and mortgage claim attachment','Principal, interest, escrow, arrears, fee and charge reconciliation','Payment history','Claims bar date','Plan and confirmation-order abstraction','Pre-petition arrears treatment','Post-petition payment records','Payment-change and post-petition fee notice support','Critical dates','Motion-for-relief referral','Final cure and final payment records','Dismissal, conversion, discharge and closure','Servicing-system reconciliation','Investor, counsel and client reporting')
$mortgageOutputs = @('Loan-document index','Missing-document tracker','Collateral exception tracker','Payment-history reconciliation','Escrow worksheet','Advance worksheet','Delinquency dashboard','Borrower-response tracker','Loss-mitigation checklist','Evaluation-input workbook','Foreclosure milestone tracker','Title-defect tracker','Counsel referral package','Mortgage-bankruptcy claim workbook','Proof-of-claim support package','Pre-petition and post-petition payment trackers','Fee and expense reconciliation','Investor and client reporting files','Quality report','Exception report','Closing checklist')

$mortgageMain = @"
<section class="page-hero service-detail-hero"><div class="container narrow"><p class="eyebrow">Primary service line</p><h1>Mortgage Servicing and Default Operations</h1><p class="lead">Operational support across loan-document administration, account reconciliation, delinquency, loss mitigation, foreclosure and bankruptcy workflows.</p><p>A mortgage file changes as payments are applied, escrow items are adjusted, borrower circumstances change, documents are received, loss-mitigation options are evaluated, legal action begins or bankruptcy interrupts the ordinary servicing path.</p><p>Axentra keeps the loan record, borrower information, payment history, servicing event, legal milestone, exception and next action aligned within the client's operating environment. Delivery follows client-approved servicing rules, investor requirements, systems, templates and escalation routes.</p><a class="button primary" href="$BasePath/contact.html?service=mortgage">Discuss Mortgage Operations</a></div></section>
<section class="section process-section"><div class="container"><div class="section-heading"><p class="eyebrow">Mortgage workflow</p><h2>A controlled record across servicing and default events</h2></div>$(Get-ProcessMarkup -Items $mortgageProcess -Label 'Mortgage servicing and default workflow')</div></section>
<section class="section section-muted"><div class="container"><div class="section-heading split-heading"><div><p class="section-index">01</p><p class="eyebrow">Loan and document onboarding</p><h2>Match the source documents to the system record</h2></div><p>The onboarding record identifies missing collateral material, data differences and servicing-transfer exceptions without providing a title opinion.</p></div>$(Get-ScopePanel -Title 'Loan and document onboarding scope' -Items $mortgageOnboarding -Open)</div></section>
<section class="section calculations-section"><div class="container detail-layout"><div class="section-intro"><p class="section-index">02</p><p class="eyebrow">Mortgage calculations and account reconciliation</p><h2>Keep balances, advances and payment history explainable</h2><p>Calculations follow the client's approved servicing methodology, loan documents, investor requirements, applicable system rules and authorised review process.</p></div><div>$(Get-ScopePanel -Title 'Calculation and reconciliation scope' -Items $mortgageCalculations -Open)<p class="boundary-note compact-boundary">Axentra does not independently determine amounts legally recoverable from a borrower.</p></div></div></section>
<section class="section section-muted"><div class="container"><div class="section-heading split-heading"><div><p class="section-index">03</p><p class="eyebrow">Delinquency and early-default support</p><h2>Record contact activity, missing information and next action</h2></div><p>Communication and collection activity remains within the client's authorised and compliant process. This page does not represent Axentra as a debt collector or payment recipient.</p></div>$(Get-ScopePanel -Title 'Delinquency and early-default scope' -Items $mortgageDelinquency -Open)</div></section>
<section class="section"><div class="container"><div class="section-heading split-heading"><div><p class="section-index">04</p><p class="eyebrow">Loss-mitigation administration</p><h2>Keep the package, decision inputs and deadlines aligned</h2></div><p>Eligibility, credit, legal and investor decisions remain within the authorised lender, servicer, investor or counsel process.</p></div>$(Get-ScopePanel -Title 'Loss-mitigation administration scope' -Items $mortgageLossMitigation -Open)</div></section>
<section class="section section-dark"><div class="container"><div class="section-heading split-heading"><div><p class="section-index">05</p><p class="eyebrow">Foreclosure and legal-process administration</p><h2>Track referral readiness and legal milestones</h2></div><p>Axentra supports operational records and status tracking. It does not conduct foreclosure, provide legal strategy, sign pleadings or act as foreclosure counsel.</p></div>$(Get-ScopePanel -Title 'Foreclosure administration scope' -Items $mortgageForeclosure -Open)</div></section>
<section class="section"><div class="container detail-layout"><div class="section-intro"><p class="section-index">06</p><p class="eyebrow">Mortgage servicing under bankruptcy</p><h2>Reconcile the loan record with the bankruptcy case</h2><p>A borrower filing changes servicing actions, claim preparation, payment treatment, legal holds and reporting. The mortgage and bankruptcy workflows remain distinct but connected.</p><a class="text-link" href="$BasePath/services/bankruptcy-operations.html">Explore Bankruptcy Operations</a></div><div>$(Get-ScopePanel -Title 'Mortgage-bankruptcy interface scope' -Items $mortgageBankruptcy -Open)</div></div></section>
<section class="section scope-confirmation"><div class="container compact-split"><div><p class="eyebrow">Scope confirmation</p><h2>Performing-loan and post-foreclosure activities require separate confirmation</h2></div><p>Those activities are excluded from the standard public scope until the operating role, systems experience, licensing position and client-authorised responsibilities are confirmed.</p></div></section>
<section class="section outputs-section"><div class="container"><div class="section-heading"><p class="eyebrow">Typical delivery outputs</p><h2>Records for reconciliation, milestones and exceptions</h2></div>$(Get-ListMarkup -Items $mortgageOutputs -ClassName 'output-list')</div></section>
$(Get-ContactBand -Eyebrow 'Mortgage operations' -Heading 'Review a loan-record, default or bankruptcy-interface workflow' -Copy 'Share the portfolio stage, approved system, investor requirements, role boundaries, calculation method and reporting requirement.')
"@

Write-SiteFile -Path 'services/mortgage-servicing-default-operations.html' -Content (Get-Page -Title 'Mortgage Servicing and Default Operations | Axentra' -Description 'Mortgage servicing and default operations support for loan documents, account reconciliation, delinquency, loss-mitigation administration, foreclosure tracking and bankruptcy interface.' -Canonical "$SiteUrl/services/mortgage-servicing-default-operations.html" -Active 'services' -Main $mortgageMain -BodyClass 'service-detail-page mortgage-page')

# Contract and Commercial Operations
$contractProcess = @('Business Request','Information Readiness','Template or Negotiating Position','Draft and Redline History','Approvals and Deviations','Executed Contract','Repository and Metadata','Obligations and Changes','Commercial Follow-Through','Evidence and Reporting')
$contractPre = @('Intake and request triage','Information and document readiness','Drafting from approved templates','First-level review preparation','Clause comparison','Deviation identification','Redline and negotiation tracking','Approval coordination','Version control','Supporting-document checks')
$contractExecution = @('Final-version verification','Signature coordination','Execution-status tracking','Document collation','Filing','Repository preparation')
$contractPost = @('Repository administration','Metadata','Renewal and expiry tracking','Obligation tracking','Notice requirements','Amendment and variation tracking','Commercial-term tracking','Exception management','Reporting','Data clean-up','Quality review')
$commercialTerms = @('Fees, fixed charges and variable charges','Usage charges and revenue share','Percentage rent and minimum guarantees','Escalations and indexation','Sponsorship payments','Rebates, credits and incentives','Commissions and discounts','Pass-through charges, service charges and operating expenses','Payment milestones, retention and holdbacks','Bonus payments, service credits and penalties','Liquidated amounts','Caps, floors and thresholds','Renewal pricing and termination payments','Taxes and withholding','Audit and reconciliation rights')
$commercialLogic = @('Value','Trigger','Calculation basis','Threshold','Frequency','Effective period','Adjustment mechanism','Dependency','Exception','Notice','Owner','Evidence','Review status')
$commercialUses = @('Revenue assurance','Margin review','Billing readiness','Lease administration','Sponsorship management','Rebate recovery','Supplier-credit tracking','Fee reconciliation','Commercial reporting','Post-signature obligation management')

$contractMain = @"
<section class="page-hero service-detail-hero"><div class="container narrow"><p class="eyebrow">Primary service line</p><h1>Contract and Commercial Operations</h1><p class="lead">A contract does not end at signature.</p><p>The approved commercial and legal position must remain connected to approvals, deliverables, notices, fees, pricing changes, obligations, renewals, variations and supporting evidence.</p><a class="button primary" href="$BasePath/contact.html?service=contracts">Discuss Contract Operations</a></div></section>
<section class="section process-section"><div class="container"><div class="section-heading"><p class="eyebrow">Contract operating thread</p><h2>From business request to commercial evidence</h2></div>$(Get-ProcessMarkup -Items $contractProcess -Label 'Contract and commercial operations workflow' -ClassName 'process-ten')</div></section>
<section class="section section-muted"><div class="container"><div class="section-heading"><p class="eyebrow">Contract lifecycle</p><h2>Keep decisions and changes with the agreement record</h2></div><div class="scope-grid three-column">$(Get-ScopePanel -Title 'Pre-execution' -Items $contractPre -Open)$(Get-ScopePanel -Title 'Execution' -Items $contractExecution -Open)$(Get-ScopePanel -Title 'Post-execution' -Items $contractPost -Open)</div></div></section>
<section class="section commercial-logic-section"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Commercial abstraction and logic</p><h2>A commercial value without its governing logic may be misleading.</h2></div><p>Operational data connects the value to the event, period, condition, exception, owner and evidence that determine how it applies.</p></div><div class="commercial-grid"><div class="commercial-panel"><h3>Commercial terms</h3>$(Get-ListMarkup -Items $commercialTerms)</div><div class="commercial-panel logic-panel"><h3>Capture the value with</h3>$(Get-ListMarkup -Items $commercialLogic)</div></div></div></section>
<section class="section section-dark"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Operational relevance</p><h2>Turn contract language into controlled follow-through</h2><p>The structured record supports finance, procurement, property, commercial and legal teams without separating the extracted value from its legal context.</p></div><div>$(Get-ListMarkup -Items $commercialUses -ClassName 'output-list light-output')</div></div></section>
$(Get-ContactBand -Eyebrow 'Contract and commercial operations' -Heading 'Review a contract lifecycle or commercial-data workflow' -Copy 'Share the contract type, playbook, approval model, repository, commercial fields and post-signature reporting requirement.')
"@

Write-SiteFile -Path 'services/contract-commercial-operations.html' -Content (Get-Page -Title 'Contract and Commercial Operations | Axentra' -Description 'Contract and commercial operations covering intake, approved-template drafting, review coordination, execution, repositories, obligations and condition-aware commercial abstraction.' -Canonical "$SiteUrl/services/contract-commercial-operations.html" -Active 'services' -Main $contractMain -BodyClass 'service-detail-page contract-page')

# Product and AI Operations
$productProcess = @('Test','Validate','Classify Errors','Identify Patterns','Recommend Logic Changes','Retest','Measure Improvement')
$productUat = @('Requirement review and acceptance criteria','User journeys and workflow scenarios','Test cases, scripts and data','Document packs','Role and permission testing','Intake and workflow routing','Approval, reminder and escalation testing','Document linking and version testing','Search and filter validation','Reporting validation','Defect recording and reproduction steps','Screenshots and source evidence','Defect classification and prioritisation support','Retesting and regression testing','Release-readiness reporting')
$productClause = @('Clause presence and absence','Classification and text boundaries','Parties, dates and defined terms','Cross-references and amendments','Order of precedence','Conditions, exceptions and qualifications','Rights, obligations and restrictions','Renewal, termination and notice','Commercial terms','Source-document linkage','Confidence flags','Missing, incomplete or incorrect extraction')
$productSummary = @('Accuracy against source','Missing conditions and qualifications','Unsupported conclusions','Incorrect party attribution','Loss of defined-term meaning','Incorrect amendment treatment','Omitted dates, values or dependencies','Overstated rights or obligations','Simplification-induced ambiguity','Suitability for the intended user')
$productErrors = @('False positives and false negatives','Missed clause structures and wording variants','Formatting issues','Amendment and document-hierarchy failures','High-review fields','Summary inconsistencies','Prompt and playbook gaps','Extraction-rule gaps','Confidence-threshold issues','Edge cases','Regression scenarios')
$productOutputs = @('Error taxonomy','Field-level and clause-level findings','Trend analysis','Recurring exception report','Source examples','Logic and prompt recommendations','Playbook recommendations','Updated validation criteria','Edge-case library','Regression test pack','Before-and-after comparison','Release-readiness report')

$productMain = @"
<section class="page-hero service-detail-hero"><div class="container narrow"><p class="eyebrow">Primary service line</p><h1>Product and AI Operations</h1><p class="lead">Domain-led testing, output assurance and improvement analysis for legal, contract and property technology.</p><p>A product may function technically and still fail where legal language, business rules and user behaviour meet. A clause may be extracted but classified incorrectly. A summary may omit a qualification. A commercial field may appear without the condition that determines when it applies.</p><p>Axentra supports product teams through domain-led testing, output validation, exception analysis and structured improvement feedback.</p><a class="button primary" href="$BasePath/contact.html?service=product-ai">Discuss Product Assurance</a></div></section>
<section class="section process-section"><div class="container"><div class="section-heading split-heading"><div><p class="eyebrow">Validation to improvement</p><h2>Correct the output. Learn from the pattern.</h2></div><p>Validation corrects the current output. Structured error analysis helps improve the next batch.</p></div>$(Get-ProcessMarkup -Items $productProcess -Label 'Product validation to improvement cycle')</div></section>
<section class="section section-muted"><div class="container detail-layout"><div class="section-intro"><p class="section-index">01</p><p class="eyebrow">UAT and release assurance</p><h2>Test the product through the work it is expected to support</h2><p>Axentra provides domain and business UAT. This service does not constitute source-code, penetration, performance, security or automated testing.</p></div><div>$(Get-ScopePanel -Title 'Domain and business UAT scope' -Items $productUat -Open)</div></div></section>
<section class="section"><div class="container"><div class="section-heading"><p class="section-index">02</p><p class="eyebrow">AI output assurance</p><h2>Validate both the extracted field and its source context</h2></div><div class="scope-grid">$(Get-ScopePanel -Title 'AI clause extraction validation' -Items $productClause -Open)$(Get-ScopePanel -Title 'AI-generated summary validation' -Items $productSummary -Open)</div></div></section>
<section class="section section-dark"><div class="container"><div class="section-heading split-heading"><div><p class="section-index">03</p><p class="eyebrow">Recurring-error analysis</p><h2>Convert repeated corrections into structured feedback</h2></div><p>Axentra does not treat every correction as an isolated review event. Findings are classified and translated into recommendations for product logic, prompts, extraction instructions, playbooks, test cases and review rules.</p></div><div class="scope-grid">$(Get-ScopePanel -Title 'Patterns examined' -Items $productErrors -Open)$(Get-ScopePanel -Title 'Typical outputs' -Items $productOutputs -Open)</div><p class="boundary-note dark-boundary">Recommendations are provided to the client's legal, product, operational, data or engineering team for review and implementation. Axentra does not claim to train or retrain AI models.</p></div></section>
$(Get-ContactBand -Eyebrow 'Product and AI operations' -Heading 'Review a release, extraction or summary-validation requirement' -Copy 'Share the product workflow, intended users, source documents, acceptance criteria, known defects and release evidence required.')
"@

Write-SiteFile -Path 'services/product-ai-operations.html' -Content (Get-Page -Title 'Product and AI Operations | Axentra' -Description 'Domain-led UAT, AI clause extraction and summary validation, defect analysis, recurring-error trends, logic recommendations and regression testing.' -Canonical "$SiteUrl/services/product-ai-operations.html" -Active 'services' -Main $productMain -BodyClass 'service-detail-page product-page')

# Defined Legal Support
$definedLegalScope = @('Legal research','Case-law research','Research summaries','Chronologies','Drafting from approved templates','Document review','Document classification','Due diligence','Matter administration','Evidence indexing','Regulatory research','Public-record research','Patent research','Prior-art research','Structured legal reporting')
$definedAssignment = @('Question','Jurisdiction','Expected sources','Available information','Unavailable information','Assumptions','Output','Citation requirements','Review responsibility','Open issues','Completion status')

$definedLegalMain = @"
<section class="page-hero service-detail-hero"><div class="container narrow"><p class="eyebrow">Supporting service line</p><h1>Defined Legal Support</h1><p class="lead">Research, document and matter support organised around a clear question, source set, output and review responsibility.</p><p>The scope stays bounded. Each assignment records what is being asked, what information is available, which sources are expected and where professional review remains required.</p><a class="button primary" href="$BasePath/contact.html?service=defined-legal">Discuss Defined Legal Support</a></div></section>
<section class="section section-muted"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Service scope</p><h2>Structured support for document-intensive legal work</h2><p>Patent work is limited to research and prior-art support. The service does not include patent prosecution, patentability opinions or unrestricted scientific expertise.</p></div><div>$(Get-ScopePanel -Title 'Defined legal support activities' -Items $definedLegalScope -Open)</div></div></section>
<section class="section"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Assignment record</p><h2>Make the question and the review boundary explicit</h2><p>A structured brief reduces ambiguity and preserves the basis for the final output.</p></div><div>$(Get-ListMarkup -Items $definedAssignment -ClassName 'output-list')</div></div></section>
$(Get-ContactBand -Eyebrow 'Defined legal support' -Heading 'Start with the question, jurisdiction and expected source set' -Copy 'Axentra will map the output, assumptions, citation standard, open issues and authorised review responsibility.')
"@

Write-SiteFile -Path 'services/defined-legal-support.html' -Content (Get-Page -Title 'Defined Legal Support | Axentra' -Description 'Defined legal support for research, approved-template drafting, document review, chronologies, due diligence, evidence indexing and structured reporting.' -Canonical "$SiteUrl/services/defined-legal-support.html" -Active 'services' -Main $definedLegalMain -BodyClass 'service-detail-page legal-support-page')

# Workflow Assessment
$assessmentQuestions = @('What event starts the work?','What information and documents are required?','Which decisions remain with the client?','Which activities move into the delivery team?','What systems and access are involved?','What exceptions interrupt the ordinary process?','What proves that the work is complete?')
$assessmentOutputs = @('Scope map','Responsibility map','Information map','Access map','Process flow','Review points','Control points','Exception categories','Staffing requirements','Skill requirements','Reporting measures','Transition dependencies','Pilot recommendation')
$assessmentProcess = @('Trigger','Inputs','Decisions','Delivery Activities','Systems and Access','Exceptions','Completion Evidence')

$assessmentMain = @"
<section class="page-hero service-detail-hero"><div class="container narrow"><p class="eyebrow">Supporting service line</p><h1>Workflow Assessment</h1><p class="lead">A requirement does not need to fit a pre-labelled service page.</p><p>Axentra evaluates the workflow, information, systems, required skills, data sensitivity, review model, exceptions and evidence of completion before establishing the delivery structure.</p><a class="button primary" href="$BasePath/contact.html?service=assessment">Discuss a Workflow</a></div></section>
<section class="section process-section"><div class="container"><div class="section-heading"><p class="eyebrow">Assessment sequence</p><h2>Understand the operating requirement before configuring delivery</h2></div>$(Get-ProcessMarkup -Items $assessmentProcess -Label 'Workflow assessment sequence')</div></section>
<section class="section section-muted"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Seven assessment questions</p><h2>Define what moves, what stays and what proves completion</h2><p>Design-thinking methods are used where they help clarify users, constraints, handoffs and operating evidence. The method is selected for the requirement rather than treated as a fixed ceremony.</p></div><ol class="assessment-questions">$(for ($i = 0; $i -lt $assessmentQuestions.Count; $i++) { '<li><span>{0:D2}</span><strong>{1}</strong></li>' -f ($i + 1), $assessmentQuestions[$i] })</ol></div></section>
<section class="section"><div class="container detail-layout"><div class="section-intro"><p class="eyebrow">Typical outputs</p><h2>A practical basis for scope and transition</h2><p>The assessment documents dependencies and unresolved items before workload moves into delivery.</p></div><div>$(Get-ListMarkup -Items $assessmentOutputs -ClassName 'output-list')</div></div></section>
$(Get-ContactBand -Eyebrow 'Workflow assessment' -Heading 'Bring the current process and the points where clarity is lost' -Copy 'The discussion starts with the trigger, information, owners, systems, decisions, exceptions and evidence expected at closure.')
"@

Write-SiteFile -Path 'services/workflow-assessment.html' -Content (Get-Page -Title 'Workflow Assessment | Axentra' -Description 'Axentra workflow assessment maps triggers, information, systems, responsibilities, controls, exceptions, review points and evidence of completion.' -Canonical "$SiteUrl/services/workflow-assessment.html" -Active 'services' -Main $assessmentMain -BodyClass 'service-detail-page assessment-page')
